### ISSUE TITLE
Compilation of O_tau_ins fails on unstable branch for complex version

### ISSUE THREAD

**Issue by aichhorn** [TRIQS/cthyb#102]
I am trying to compile the latests cthyb unstable in complex version. I get the following compilation error:

[ 25%] Building CXX object c++/triqs_cthyb/CMakeFiles/cthyb_c.dir/measures/O_tau_ins.cpp.o
/Users/aichhorn/Codes/cthyb.src/c++/triqs_cthyb/measures/O_tau_ins.cpp:52:18: error: no viable
      conversion from 'complex<double>' to 'const double'
    const double prefactor = s / bare_atomic_weight / bare_atomic_reweighting / double(nsamples);

This line was inserted in commit 66827a1. Reverting one commit back to d165b5e (O_tau_ins update), the compilation works, but the following tests fail:
The following tests FAILED:
	 18 - single_site_bethe (Failed)
	 26 - O_tau_ins (Failed)
	 31 - setup_Delta_tau_and_h_loc_complex (Failed)

Test 18 might be related to precision problems (there are later commints on that), but I have no idea about the other two tests.

These problems arise in exactly the same way on both Mac OSX, clang 6.0, and on debian with gcc-7.3.

**Comment by HugoStrand** [comment]
Dear Markus,

Thank you for reporting. This is a bug that I will fix asap.

Cheers, Hugo

**Comment by HugoStrand** [comment]
Dear Markus, 

I have fixed the bug on the `cthyb/unstable` branch see:
https://github.com/TRIQS/cthyb/commit/8430e2c1d7ab56f8c96f943d2b9d7220049e0858#diff-628e3f6786b56480b3c5471ff4c5abd3L52

I have another problem with the `histogram` test that is not passing. But it pertains only to the case when using the `performance_analysis` option set to `True`, which is not the normal mode of operation.

Could you please try pulling unstable and running the tests?

Cheers, Hugo

**Comment by aichhorn** [comment]
Hi Hugo,
Thanks a lot! I pulled the newest commit, and now the compilation for the complex version works on both debian and Mac, all tests (in normal mode) pass!
Best,
Markus
