### ISSUE TITLE
CTHYB with particle number restrictions

### ISSUE THREAD

**Issue by dmantadakis** [TRIQS/cthyb#103]
Dear All,
Based on the development of the atom_diag is it now possible to restrict the impurity solution such that we consider only a fraction of the configurations? For example, in a full d-shell to consider only the particle subspaces with 0,1,2,3,4 electrons?
Best,
Danny

**Comment by HugoStrand** [comment]
Dear @dmantadakis , 

I was pushing for getting back the functionality of restricting the Hilbert space in `triqs/atom_diag` and got help from @krivenko to make that happen. This is right now part of `triqs/master` and will be part of `triqs/2.1`. I have not taken the time to expose this inside of `cthyb` yet. If you want it asap you can add the parameters to cthyb and send a pull request and I will look over it and merge. If not it will not be done before APS 2019, I am sorry.

Cheers, Hugo

**Comment by HugoStrand** [comment]
Dear @dmantadakis,

@krivenko just fixed this and it is available on unstable, for details see #105.

Best, Hugo

**Comment by HugoStrand** [comment]
Oh! Please do reopen this if you experience any issues.
