### ISSUE TITLE
Local susceptibility (question)

### ISSUE THREAD

**Issue by dmantadakis** [TRIQS/cthyb#106]
Dear All, 
When trying to measure a correlator <A(tau)A(0)> where A is an operator that doesn't commute with the local Hamiltonian, the CTHYB (unstable) throws an error. I was wondering, if such a restriction is that important and if there is any way with the current implementation to overcome this issue. 
Best,
Danny

**Comment by HugoStrand** [comment]
Dear @dmantadakis,

As far as I understand the measurement by insertion of operators O_1 and O_2 that does not commute with the local Hamiltonian, [O_i, H] \ne 0, is "non-ergodic". But I can not give a good explanation of what goes wrong.

During implementation I tried general (density) operators on a simple model and compared to the exact result from `pyed` (https://github.com/HugoStrand/pyed) that can compute arbitrary operator combinations.

The bottom line is that the comparison showed directly that cthyb does not give the right answer.

This could of course be problem dependent, so if you really want, you can disable the check of the commutator.

But then I would not trust the result without making extra sanity checks. One test is to compute the local many body density matrix and compute the static expectation values <O_1 O_2> from that and compare to the measured response at \tau = 0 and \beta. Another test is to compute the static susceptibility by an applied field F * O_2 and extrapolate the zero field response. That should be the same as the integral in \tau of the measure susceptibility.  -d<O_1>/d F|_{F=0} = \int_0^\beta d\tau <O_1(\tau) O_2(0)>.

Cheers, Hugo

**Comment by dmantadakis** [comment]
Dear @HugoStrand 
Thanks for your detailed comment!
Best, Danny
