### ISSUE TITLE
Spin autocorrelation function

### ISSUE THREAD

**Issue by CripleH** [TRIQS/cthyb#107]
Dear all,

We are interested in calculating the spin autocorrelation function <S(tau)S(0)> in LDA+DMFT calculations (as in PRL 87:067205). Can this be measured with the ct-hyb solver, and how?

Best,
Marcus

**Comment by HugoStrand** [comment]
Dear @CripleH, 

The 2.1.x branch is able to measure the retarded response of any set of operators that commute with your local hamiltonian. Please have a look at the documentation:

https://triqs.github.io/cthyb/2.1.x/reference/measurements.html

**Comment by CripleH** [comment]
Thank you!
