### ISSUE TITLE
Module not found with Python3 

### ISSUE THREAD

**Issue by JonasRigo** [TRIQS/cthyb#108]
Hi,

I was able to install TRIQS and CTHYB without any problems and I also ran code successfully using python 2.7. But when I use python 3.6 I get the erorr

ModuleNotFoundError: No module named 'cpp2py_info_base'

When I run the code in the site-packages/cpp2py directory i get this error

ModuleNotFoundError: No module named 'mesh_point'

So, I assume that I miss some path variables, is this true? If so, which are the variables I have to set?

Thanks!

**Comment by Wentzell** [comment]
Hey @JonasRigo 
We do currently only support Python 2. Moving to Python 3 is however high on our priority list.
