### ISSUE TITLE
Two-particle Green’s functions Data

### ISSUE THREAD

**Issue by JonasRigo** [TRIQS/cthyb#110]
Dear cthyb developers,

I'm trying to calculate the local susceptibility for the Single Impurity Anderson Model as a test in cthyb version 2.8.12.
The solver is measuring blocks, so I have

measure_G2_blocks = set([("up","up"),("down","down"),("up","down"),("down","up")])

When I try then to call G2_tau from the HDFArchive I would use 

oplot(ar['G2_tau'][("up","up")], '-o', x_window = (0,50))

to plot that particular block. At that point I get the error 

TypeError: exceptions must be old-style classes or derived from BaseException, not NotImplementedType

So, my question is if I am doing something wrong or is this really not implemented yet?
Other than that, is there a simpler/already implemented way to measure the local susceptibility? I read in an other thread that, apparently, in version 2.x.  something like this should be possible, but I found no documentation regarding to it.

Thanks!

Best wishes,
Jonas

**Comment by HugoStrand** [comment]
Dear Jonas,

Thank you for posting!

The sampling is implemented, however, the "automagic" plotting in the Triqs library is unfortunately not implemented. 

For manual ways of looking at the data please see the measure_G2 benchmarks and the jupyter notebooks there:

https://github.com/TRIQS/cthyb/tree/master/benchmark/measure_g2/nonint_2bath

Cheers, Hugo
