### ISSUE TITLE
Complex Interaction Hamiltonian

### ISSUE THREAD

**Issue by JonasRigo** [TRIQS/cthyb#111]
Dear CTHYB Developers,

When defining the interaction Hamiltonian with complex valued couplings (in the pythonian way) the solver gives me this error (version: 2.8.12):
____________________________________
TypeError: 
---- There is 1 error in Python -> C++ transcription for the class triqs_cthyb::solve_parameters_t

1 The parameter h_int does not have the right type : expecting triqs_cthyb::many_body_op_t in C++, but got 'pytriqs.operators.operators.Operator' in Python.
_____________________________________

I ran the cmake with the complex option enabled, so I am pretty sure that I mistake the definition. So, my question is what is the proper way to define a Hamiltonian with complex values?

Thanks a lot!

Best regards, Jonas

**Comment by HugoStrand** [comment]
Dear Jonas,

Thank you for reporting the problem.
Can you try to reproduce the error with a simplified python script, so that we can reproduce the error?
Normally this conversion should be automatic and not give an error.

Best regards,
Hugo

**Comment by JonasRigo** [comment]
Dear Hugo,

Thanks for the quick reply!

This python script produces the same error I've reported:
[Issue111.txt](https://github.com/TRIQS/cthyb/files/3060144/Issue111.txt)

Best regards,
Jonas

**Comment by HugoStrand** [comment]
Dear Jonas,

I have tried your example and it works nicely on the 2.1.x branch. Here is a compressed version
```python
import numpy as np
from pytriqs.operators import c, c_dag
from pytriqs.gf import Gf, MeshImFreq, SemiCircular, inverse, iOmega_n
from triqs_cthyb.solver import Solver

beta = 50
gf_struct = [ ['gf',[0,1]] ]

delta_iw = Gf(mesh=MeshImFreq(beta,'Fermion', 1025), target_shape=[2, 2])
delta_iw *= 0.
delta_iw[(0,0)] << 0.1**2 * SemiCircular(1.)

h_loc = np.matrix([
    [-.1, .5],
    [ .5,-.1]])

h_int = 1.j*(c('gf',0)*c('gf',1) - c_dag('gf',1)*c_dag('gf',0))

S = Solver(beta=beta, gf_struct=gf_struct)
S.G0_iw['gf'] << inverse(iOmega_n - h_loc - delta_iw)
S.solve(
    h_int=h_int,
    n_cycles=1000,
    length_cycle=200,
    n_warmup_cycles=1000,
    )
```
Could you try it using `triqs/2.1.x` and `cthyb/2.1.x` ?

Best regards,
Hugo

```
void [rigol] $ p issue111.py
Starting on 1 Nodes at : 2019-04-09 13:44:19.312443

╔╦╗╦═╗╦╔═╗ ╔═╗  ┌─┐┌┬┐┬ ┬┬ ┬┌┐ 
 ║ ╠╦╝║║═╬╗╚═╗  │   │ ├─┤└┬┘├┴┐
 ╩ ╩╚═╩╚═╝╚╚═╝  └─┘ ┴ ┴ ┴ ┴ └─┘

The local Hamiltonian of the problem:
(0,1)*c_dag('gf',0)*c_dag('gf',1) + (0.5,0)*c_dag('gf',0)*c('gf',1) + (-0.1,0)*c_dag('gf',0)*c('gf',0) + (-0.1,0)*c_dag('gf',1)*c('gf',1) + (0.5,0)*c_dag('gf',1)*c('gf',0) + (0,-1)*c('gf',1)*c('gf',0)
Using autopartition algorithm to partition the local Hilbert space
Found 2 subspaces.

Warming up ...
13:44:19  53% ETA 00:00:00 cycle 531 of 1000

Accumulating ...
13:44:19  56% ETA 00:00:00 cycle 564 of 1000


[Rank 0] Collect results: Waiting for all mpi-threads to finish accumulating...
WARNING: Tau discontinuity of G_tau deviates appreciably from -1
     .... max_element |g(0) + g(beta) + 1| = 1
[Rank 0] Timings for all measures:
Measure            | seconds   
Average sign       | 0.000193063
G_tau measure      | 0.000443315
Total measure time | 0.000636378
[Rank 0] Acceptance rate for all moves:
Move set Insert two operators: 0.0417656
  Move  Insert Delta_gf: 0.0417656
Move set Remove two operators: 0.0418324
  Move  Remove Delta_gf: 0.0418324
Move  Shift one operator: 0.00859306
[Rank 0] Warmup lasted: 0.185004 seconds [00:00:00]
[Rank 0] Simulation lasted: 0.17979 seconds [00:00:00]
[Rank 0] Number of measures: 1000
Total number of measures: 1000
Average sign: (1,0)
```

**Comment by JonasRigo** [comment]
Dear Hugo,

I've switched the branch and I think I've found the reason for the error. When executing cmake with the necessary variables for complex couplings I get the following error:
___
CMake Warning:
  Manually-specified variables were not used by the project:
    
   HYBRIDISATION_IS_COMPLEX
    LOCAL_HAMILTONIAN_IS_COMPLEX
___

As far as I can tell this is not a known issue. Do you have any idea why this occurs?

Thanks a lot.

Best regards,
Jonas

**Comment by HugoStrand** [comment]
Dear Jonas,

I am afraid the naming of these parameters has changed you have to pass 
```
  -DHybridisation_is_complex=On \
  -DLocal_hamiltonian_is_complex=On \
```
To cmake to get the fully complex version of the solver.

Best regards,
Hugo

**Comment by HugoStrand** [comment]
The change has occurred between `master` and `unstable`. 
Here is the install documentation for the upcoming 2.1.x version:
https://triqs.github.io/cthyb/2.1.x/install.html

**Comment by JonasRigo** [comment]
Dear Hugo,

Thanks for the clarification!

Best wishes, 
Jonas
