### ISSUE TITLE
Disable GF2 test when the GF2 build flag is set to off

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/cthyb#112]
This is a "bug" report. When building cthyb without two-particle Green's function sampling using the cmake flag, the g2 sampling test is still active, executed during testing, and (of course) fails since there is no g2 sampling compiled.

Todo: Adjust the test so that it is not run when the g2 cmake flag is set to OFF.

Thank you @mzingl for reporting!

**Comment by Wentzell** [comment]
@HugoStrand @mzingl
I cannot reproduce this problem on unstable.
Was this behavior observed on 2.1.x ?

**Comment by mzingl** [comment]
Yes, I had it today on 2.1.x

**Comment by Wentzell** [comment]
This is fixed, c.f. 71ee3b7
