### ISSUE TITLE
Orbital resolved spin autocorrelation function

### ISSUE THREAD

**Issue by johanjoensson** [TRIQS/cthyb#120]
Hello!
I was wondering if there is a way to get the individual orbital contributions to the spin autocorrelation function?

Best regards
Johan Jönsson

**Comment by Wentzell** [comment]
Dear @johanjoensson,

You should be able to measure bosonic correlation functions by using the `measure_O_tau` option
of the solver described [here](https://triqs.github.io/cthyb/2.1.x/reference/measurements.html?highlight=measure_o_tau#local-susceptibility-and-other-operator-pairs)

**Comment by Wentzell** [comment]
A guide show-casing the use of this measurement can be found [here](https://triqs.github.io/cthyb/2.1.x/guide/dynamic_susceptibility_notebook.html)

**Comment by johanjoensson** [comment]
Thank you!
Maybe I should clarify my question a bit. Let's say I have a system of d-electrons and I would like to measure the spin autocorrelation function. Using the Sz operator and measuring <Sz(t)Sz(0)> would give me the total spin autocorrelation function (for all the d-states). But if my d-electrons can be split into eg and t2g states (or something similar), would it be possible to measure the spin autocorrelation function e.g. of the t2g states only? If it is possible how should I define the spin operator?

Thanks in advance,
Johan Jönsson

**Comment by HugoStrand** [comment]
Dear Johan,

The sampling implemented in `triqs_cthyb` is limited to operators that commute with the local Hamiltonian `H`, for very technical reasons. So whether you can measure t2g and eg spin susceptibility separately depends on whether your system has the required symmetry.

The spin operator you can either build by hand using the `triqs` second quantization operators. Or use some convenience function in the library, please see

https://github.com/TRIQS/triqs/blob/2.1.x/pytriqs/operators/util/observables.py#L47

Best, Hugo

**Comment by johanjoensson** [comment]
Thank you very much for the reply Hugo!

Regards
Johan Jönsson
