### ISSUE TITLE
cthyp for triqs1.4

### ISSUE THREAD

**Issue by 3guk37** [TRIQS/cthyb#121]
Hello TRIQS team, is there a older version cthyp for triqs1.4?

**Comment by the-hampel** [comment]
Hi, 
Did you already see the "tag" feature on github? When you select the branch, you can switch to tags. They can be used to check out specific version with git by using for example the command:
`git clone -b 1.4.2 https://github.com/TRIQS/cthyb.git`
This will download the tagged version 1.4.2 of cthyb. The old documentation is available as well: https://triqs.github.io/cthyb/1.4/

There are also several other older versions available.

Hope that helps,
Alex

**Comment by 3guk37** [comment]
I didn't notice this feature. Thanks for this very fast and helpful answer!
