### ISSUE TITLE
MPI_Comm_rank() function was called before MPI_INIT was invoked.

### ISSUE THREAD

**Issue by asubedi** [TRIQS/cthyb#122]
I am running the aim.py example of cthyb.  When I run it, I get the following error:

```
Starting on 1 Nodes at : 2019-10-04 20:20:56.632662
*** The MPI_Comm_rank() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[montblanc1:07616] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[5436,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by Wentzell** [comment]
Dear @asubedi, Do all tests pass for triqs and cthyb?

**Comment by asubedi** [comment]
All tests pass for triqs.  Following tests fail for cthyb:

```
The following tests FAILED:
	 16 - setup_Delta_tau_and_h_loc (Failed)
	 17 - single_site_bethe (Failed)
	 18 - atomic_observables (Failed)
	 19 - kanamori (Failed)
	 20 - slater (Failed)
	 21 - measure_static (Failed)
	 22 - histograms (Failed)
	 23 - move_global (Failed)
	 24 - h5_read_write (Failed)
	 25 - O_tau_ins (Failed)
Errors while running CTest
make: *** [test] Error 8
```

I have -DMeasureG2=OFF because of problems with NFFT.

**Comment by Wentzell** [comment]
Could you run 

```
CTEST_OUTPUT_ON_FAILURE=1 ctest -V -R single_site_bethe
```

in the cthyb build directory and provide the output

**Comment by asubedi** [comment]
Here is the output:

```
$ CTEST_OUTPUT_ON_FAILURE=1 ctest -V -R single_site_bethe
UpdateCTestConfiguration  from :/home/subedi/softwares/TRIQS-2.1-git/cthyb.build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/subedi/softwares/TRIQS-2.1-git/cthyb.build/DartConfiguration.tcl
Test project /home/subedi/softwares/TRIQS-2.1-git/cthyb.build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 17
    Start 17: single_site_bethe

17: Test command: /home/subedi/miniconda3/envs/triqs/bin/python "/home/subedi/softwares/TRIQS-2.1-git/cthyb.src/test/python/single_site_bethe.py"
17: Environment variables: 
17:  PYTHONPATH=/home/subedi/softwares/TRIQS-2.1-git/cthyb.build/python:/home/subedi/softwares/TRIQS-2.1-git/install/lib/python2.7/site-packages:/home/subedi/softwares/TRIQS-2.1-git/install/lib/python2.7/site-packages:/home/subedi/softwares/TRIQS-2.1-git/install/lib/python2.7/site-packages:
17: Test timeout computed to be: 10000000
17: Starting on 1 Nodes at : 2019-10-04 20:41:25.825935
17: *** The MPI_Comm_rank() function was called before MPI_INIT was invoked.
17: *** This is disallowed by the MPI standard.
17: *** Your MPI job will now abort.
17: [montblanc1:46426] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
1/1 Test #17: single_site_bethe ................***Failed    0.21 sec
Starting on 1 Nodes at : 2019-10-04 20:41:25.825935
*** The MPI_Comm_rank() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[montblanc1:46426] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.21 sec

The following tests FAILED:
	 17 - single_site_bethe (Failed)
Errors while running CTest
```

**Comment by asubedi** [comment]
BTW, I have gcc, mkl, mpirun, boost, fft, gmp, etc. all installed from conda.  I am not doing any module load except for the module load slurm.

**Comment by Wentzell** [comment]
The mpi module of triqs seems to fail to initialize the mpi environment.
Which version of mpi did triqs end up finding?

Can you please run 

```
python -c "import pytriqs.utility.mpi as mpi; print mpi.rank"
```

and 

```
python -c "from pytriqs import version; version.show_version(); version.show_git_hash()"
```

and let me know what you get.

**Comment by asubedi** [comment]
```
$ python -c "import pytriqs.utility.mpi as mpi; print mpi.rank"
Starting on 1 Nodes at : 2019-10-04 20:51:27.906257
0
```
```
$ python -c "from pytriqs import version; version.show_version(); version.show_git_hash()"

You are using the TRIQS library version 2.1.1


You are using the git hash ffdb3f515b45f49abc5c3f990a347f5877332b52

```

**Comment by Wentzell** [comment]
Which `libmpi.so` is detected when you run cmake for triqs itself?

**Comment by Wentzell** [comment]
I assume the problem is that you are using mpi4py from conda which is using a different `libmpi.so` than the one used by `libtriqs.so`

**Comment by Wentzell** [comment]
Mixing parts of an anaconda setup with system libraries can be a delicate business. Note however that we are preparing a separate triqs conda package atm that will be wrapped up soon.
Cf. https://github.com/conda-forge/staged-recipes/pull/9706

**Comment by asubedi** [comment]
> I assume the problem is that you are using mpi4py from conda which is using a different `libmpi.so` than the one used by `libtriqs.so`

You are right!  The problem was:

```
In [3]: mpi4py.get_include()
Out[3]: '/home/subedi/.local/lib/python2.7/site-packages/mpi4py/include'

In [5]: mpi4py.__path__
Out[5]: ['/home/subedi/.local/lib/python2.7/site-packages/mpi4py']
```
Somehow mpi4py installed using conda was not being used.  I cleaned up my .local/lib, and aim.py example works now.  All the tests of cthyb also passes.

Thanks a lot for your help in sorting this out!

**Comment by cmtcl18** [comment]
Dear All,
I am getting the same error during make test of TRIQS/CTHYB installation.

60% tests passed, 10 tests failed out of 25

Total Test time (real) =  23.75 sec

The following tests FAILED:
	 16 - setup_Delta_tau_and_h_loc (Failed)
	 17 - single_site_bethe (SEGFAULT)
	 18 - atomic_observables (SEGFAULT)
	 19 - kanamori (SEGFAULT)
	 20 - slater (SEGFAULT)
	 21 - measure_static (SEGFAULT)
	 22 - histograms (SEGFAULT)
	 23 - move_global (SEGFAULT)
	 24 - h5_read_write (SEGFAULT)
	 25 - O_tau_ins (SEGFAULT)
Errors while running CTest
Makefile:96: recipe for target 'test' failed
make: *** [test] Error 8

I went through the solution mentioned above for this issue, but did not able to sort-out it. 

I will be thankful for your suggestion.

Best Regards
CMTCL

**Comment by cmtcl18** [comment]
Dear All,
Since the issue is similar with my above issue, so I did not open a new issue. Can anyone suggest, how should I sort-out the above issue. 

With the above error, the make install for CTHYB worked successfully with command 'sudo make install'. When I run the DMFT self-consistency cycle for SrVO3, the following error is appearing. 

Traceback (most recent call last):
  File "DMFTSC.py", line 126, in <module>
    with HDFArchive(dft_filename+'.h5','a') as ar:
  File "/home/jatin/triqs/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 389, in __init__
    self._init_root( LocalFileName, open_flag)
  File "/home/jatin/triqs/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive_basic_layer_h5py.py", line 38, in _init_root
    fich = h5py.File(LocalFileName, open_flag)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 113, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2847)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2805)
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create (/build/h5py-qzs83i/h5py-2.7.1/h5py/h5f.c:2296)
IOError: Unable to create file (unable to open file: name = 'SrVO3.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)
Exception AttributeError: "HDFArchive instance has no attribute '_group'" in <object repr() failed> ignored

If you need any other information, I will happy to provide.

Best Regards
CMTCL

**Comment by Atomtomate** [comment]
This issue has been closed for a long time now. However I still get this error in v3.0. with manual compilation from source as well as the conda/mamba install. I reproduced the steps above but don't know how to check which libmpi.so is used or how to change that behavior. Would it be possible to post some guide here, since this problem seemingly still pops up on some setups.

**Comment by Wentzell** [comment]
Dear @Atomtomate,

This is very strange, as barely anything has changed in regards to mpi for v3.0.
Also we are testing TRIQS + CTHyb v3  in a number of different setups, including the conda CI without issues.

- What system are you running on?
- What are the exact commits for TRIQS / cthyb that you use?
- Please provide a minimal example script that produces the failure for you
