### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by cmtcl18** [TRIQS/cthyb#126]
Dear All,
I am trying to install TRIQS/CTHYB using  ' https://triqs.github.io/cthyb/2.1.x/index.html ' . I am getting this following error.
-- Found TRIQSConfig.cmake with version 2.2.1, hash = f3a02ae01ea4d7144e331b507f38457862926add
CMake Error at /usr/lib/cmake/triqs/TRIQSConfig.cmake:50 (message):
  For your own safety, you should use the same compiler as the one used to
  compile TRIQS!

    -- CMAKE_CXX_COMPILER: /usr/bin/g++-7
    -- TRIQS_CXX_COMPILER: /usr/bin/g++
Call Stack (most recent call first):
  CMakeLists.txt:33 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/jatin/triqs/cthyb.src/CMakeFiles/CMakeOutput.log".

For installing CTHYB, along with `cmake ../cthyb.src` which CMake options should I considered?

Best Regards
CMTCL

**Comment by the-hampel** [comment]
Hi,
This error means, that you used a different compiler for compiling triqs than you using right now for compiling cthyb. This may not fixable by specifying cmake options, you need to check which compiler you used for compiling triqs. Could it be, that you installed triqs using the apt-get command, or did you installed it manually?

Did you consider to install triqs and cthyb using the packages? 
```
sudo apt-get install -y triqs_cthyb
```

**Comment by cmtcl18** [comment]
Dear Alex,
I used command from  both  'Ubuntu Debian packages' and 'Compiling  from source (Advanced)' for TRIQS, CTHYB and also for DFTTools, MAXENT installation.

Thank you for your suggestion.

**Comment by the-hampel** [comment]
Hi,
I am not sure, if I understand that answer correctly. How can you use "both" commands from packages and compiling. Either you use the package for triqs and the applications, or you compile from source. I would not try to mix these together. Please specify how you installed triqs. Package or compiled yourself?

**Comment by the-hampel** [comment]
can we close this issue?
