### ISSUE TITLE
Are there improved self-energy estimators in CT-HYB?

### ISSUE THREAD

**Issue by katanin** [TRIQS/cthyb#135]
Are the improved self-energy estimators (via evaluation of G*\Sigma) included in either version of TRIQS/CT-HYB?

**Comment by the-hampel** [comment]
Hi @katanin,
unfortunately, this feature is not available for now in cthyb. We only provide, tail-fitting procedures and measuring legendre polynomial coefficients to reduce noise. 
Best,
Alex
