### ISSUE TITLE
Tail fitting to non-interacting Green's Function

### ISSUE THREAD

**Issue by sujanbharadwaj** [TRIQS/cthyb#136]
I am using cthyb-TRIQS to solve a model system. I have obtained the non-interacting green's function. Before passing non-interacting greens function to the solver, I have to tail fit the non-interacting green's function using known local moments. The local moments for the model that I have considered is (a0 = 1, a1 =0.5, a2 = 0.1). Please tell me how to tail fit for non-interacting green's function ( S.G0_iw ) using known moments.

**Comment by the-hampel** [comment]
Hi,
I hope I understand your question correctly. Let me first say, that in triqs the Gf object does not hold the tail properties explicitly anymore (compared to ver2.x.x). This means once fitted you will change the actual data of the Gf. Therefore, it is left to the user to fit the input to the cthyb solver manually. Fitting can be done quite easily withing python following the doc here: https://triqs.github.io/triqs/3.0.x/documentation/manual/triqs/gfs/c++/tail.html?highlight=set_tail_fit_parameters , before you feed your input to the solver:
```
# this should be your Gf or BlockGf object to fit
G0_fit = G0_orig.copy()

expansion_order = 4
shape = [0] + list(G0_fit.target_shape)
# here you have to provide your moments instead of zeros
known_moments = np.zeros(shape, dtype=np.complex)

nmin = 20
o_min = (2*nmin+1)*np.pi/beta
nmax = 60
o_max = (2*nmax+1)*np.pi/beta

tail, err = G0_fit.fit_hermitian_tail_on_window(n_min = nmin, 
                                                  n_max = nmax , 
                                                  known_moments = known_moments[0:1], 
                                                  n_tail_max = 10 * len(G0_fit.mesh) , 
                                                  expansion_order = expansion_order)

# the next line is essential to actually replace the original data with the fit after freq `nmin`
G0_fit.replace_by_tail(tail,nmin)
```
Then give `G0_fit` to the solver as `S.G0_iw=G0_fit`. Does this help you?

**Comment by sujanbharadwaj** [comment]
> Hi,
> I hope I understand your question correctly. Let me first say, that in triqs the Gf object does not hold the tail properties explicitly anymore (compared to ver2.x.x). This means once fitted you will change the actual data of the Gf. Therefore, it is left to the user to fit the input to the cthyb solver manually. Fitting can be done quite easily withing python following the doc here: https://triqs.github.io/triqs/3.0.x/documentation/manual/triqs/gfs/c++/tail.html?highlight=set_tail_fit_parameters , before you feed your input to the solver:
> 
> ```
> # this should be your Gf or BlockGf object to fit
> G0_fit = G0_orig.copy()
> 
> expansion_order = 4
> shape = [0] + list(G0_fit.target_shape)
> # here you have to provide your moments instead of zeros
> known_moments = np.zeros(shape, dtype=np.complex)
> 
> nmin = 20
> o_min = (2*nmin+1)*np.pi/beta
> nmax = 60
> o_max = (2*nmax+1)*np.pi/beta
> 
> tail, err = G0_fit.fit_hermitian_tail_on_window(n_min = nmin, 
>                                                   n_max = nmax , 
>                                                   known_moments = known_moments[0:1], 
>                                                   n_tail_max = 10 * len(G0_fit.mesh) , 
>                                                   expansion_order = expansion_order)
> 
> # the next line is essential to actually replace the original data with the fit after freq `nmin`
> G0_fit.replace_by_tail(tail,nmin)
> ```
> 
> Then give `G0_fit` to the solver as `S.G0_iw=G0_fit`. Does this help you?


Hello Alexander Hampel,

Thanks for your suggestion. I have tried the way you suggested. I have attached the code with this issue. I am encountering with "Run time error". The screenshot of the error message is attached. Please find it. However, the code works fine without tail fitting but yields non-convincing result. Please let me know the tail fitting part in the code is written properly.
[cthybtriqs.zip](https://github.com/TRIQS/cthyb/files/5453879/cthybtriqs.zip)
![Screenshot from 2020-10-28 22-53-04](https://user-images.githubusercontent.com/45603592/97475425-4127e880-1973-11eb-8f8d-172a1528e18f.png)

**Comment by the-hampel** [comment]
Hi,
that looks as if something went wrong, at least if you did not get the error before. Especially the message: "WARNING: Big error in tailfit..." means that cthyb as problems extracting the Hloc from the hybridization (which is done by looking at iw->infty for delta) Did you check the fit by storing in the h5 and simply plotting? What happens when you do not do the fit first? I think I am still not fully sure, why the fit is necessary in the example provided. 

Can you try to use only one moment instead of 3 at once, and show the raw data and the fit? In your first iteration Sigma=0 right. so you could also check the initial G_iw first with the tail fit.

The other thing that I do not understand is the choice of your moments. Why is a_0=1.0? Is your static shift in ReG=1.0? Is that correct or did you want to set the first moment to 1.0? Second, your a_1 moment seems to be negative(?) in the first iteration. (at least if I correctly looked at the set variables) I am not an expert for this, but does this make sense physically?

However, I tried again with some raw data and for me it works: 
```
# fit tail manually
S_iw_mfit = S_iw_raw.copy()

expansion_order = 4
shape = [0] + list(S_iw_mfit.target_shape)
known_moments = np.zeros(shape, dtype=np.complex)
# known_moments[0,0,0] = 6.6

print(known_moments)
nmin = 20
o_min = (2*nmin+1)*np.pi/beta
nmax = 60
o_max = (2*nmax+1)*np.pi/beta

tail, err = S_iw_mfit.fit_hermitian_tail_on_window(n_min = nmin, 
                                                  n_max = nmax , 
                                                  known_moments = known_moments, 
                                                  n_tail_max = 10 * len(S_iw_mfit.mesh) , 
                                                  expansion_order = expansion_order)


S_iw_mfit.replace_by_tail(tail,nmin)

plt.axvline(x=o_min)
plt.axvline(x=o_max)
oplot(S_iw_mfit.real,'-x',label='real')
oplot(S_iw_raw.real,'o',label='real',markersize=2)


plt.xlim(-0,50)
plt.ylim(6.0,7.0)
plt.show()
```
and it looks like this: 
![image](https://user-images.githubusercontent.com/21337117/97503319-348f9a00-194b-11eb-9a15-d9b6a18e954d.png)

where the blue vertical lines denote the fitting window and the blue solid line is the fit (all shown here for Re G(iw)). For me this looks good. This is without specifying any moments. If I specify for example the 0th moment with 6.6 the fit looks the same, as this should be the static shift the ReG approaches for iw->infty . Or did I do a mistake here? I can provide you with my raw data, but I think this example show that it should be fairly straightforward.  

If that all does not help I can try to look at your code in more detail...

**Comment by sujanbharadwaj** [comment]
> Hi,
> that looks as if something went wrong, at least if you did not get the error before. Especially the message: "WARNING: Big error in tailfit..." means that cthyb as problems extracting the Hloc from the hybridization (which is done by looking at iw->infty for delta) Did you check the fit by storing in the h5 and simply plotting? What happens when you do not do the fit first? I think I am still not fully sure, why the fit is necessary in the example provided.
> 
> Can you try to use only one moment instead of 3 at once, and show the raw data and the fit? In your first iteration Sigma=0 right. so you could also check the initial G_iw first with the tail fit.
> 
> The other thing that I do not understand is the choice of your moments. Why is a_0=1.0? Is your static shift in ReG=1.0? Is that correct or did you want to set the first moment to 1.0? Second, your a_1 moment seems to be negative(?) in the first iteration. (at least if I correctly looked at the set variables) I am not an expert for this, but does this make sense physically?
> 
> However, I tried again with some raw data and for me it works:
> 
> ```
> # fit tail manually
> S_iw_mfit = S_iw_raw.copy()
> 
> expansion_order = 4
> shape = [0] + list(S_iw_mfit.target_shape)
> known_moments = np.zeros(shape, dtype=np.complex)
> # known_moments[0,0,0] = 6.6
> 
> print(known_moments)
> nmin = 20
> o_min = (2*nmin+1)*np.pi/beta
> nmax = 60
> o_max = (2*nmax+1)*np.pi/beta
> 
> tail, err = S_iw_mfit.fit_hermitian_tail_on_window(n_min = nmin, 
>                                                   n_max = nmax , 
>                                                   known_moments = known_moments, 
>                                                   n_tail_max = 10 * len(S_iw_mfit.mesh) , 
>                                                   expansion_order = expansion_order)
> 
> 
> S_iw_mfit.replace_by_tail(tail,nmin)
> 
> plt.axvline(x=o_min)
> plt.axvline(x=o_max)
> oplot(S_iw_mfit.real,'-x',label='real')
> oplot(S_iw_raw.real,'o',label='real',markersize=2)
> 
> 
> plt.xlim(-0,50)
> plt.ylim(6.0,7.0)
> plt.show()
> ```
> 
> and it looks like this:
> ![image](https://user-images.githubusercontent.com/21337117/97503319-348f9a00-194b-11eb-9a15-d9b6a18e954d.png)
> 
> where the blue vertical lines denote the fitting window and the blue solid line is the fit (all shown here for Re G(iw)). For me this looks good. This is without specifying any moments. If I specify for example the 0th moment with 6.6 the fit looks the same, as this should be the static shift the ReG approaches for iw->infty . Or did I do a mistake here? I can provide you with my raw data, but I think this example show that it should be fairly straightforward.
> 
> If that all does not help I can try to look at your code in more detail...

Hello,
Your suggestions were very helpful. I found a bug in the code which I sorted out now. Thank you
