### ISSUE TITLE
Compiling Triqs, CTHYB, DFTtools on cluster from source

### ISSUE THREAD

**Issue by karlabaumann** [TRIQS/cthyb#138]
Dear all,

I installed with help of the Cluster administration Triqs, CTHYB and DFTtools on our cluster. 
The adiministration took care of all the necessary libraries on Ubuntu and I compiled from source Triqs, etc in my home director and the installation path. Using cmake and then make everything works fine. When I do make test it never passes all the test and when I want to run dmft code I used before on "normal" machines where we installed with sudo apt etc. it gives me the following error: 
------
No components were able to be opened in the pml framework.

This typically means that either no components of this type were
installed, or none of the installed components can be loaded.
Sometimes this means that shared libraries required by these
components are unable to be found/loaded.
------

I did some test with commenting out some things in the code. For example if I only import this modules it works without error:

from triqs.gf import *
from triqs.operators import *
from h5 import *
from matplotlib import pylab as plt
from triqs.plot.mpl_interface import 
from triqs.plot.mpl_interface import subplots

but if I also want to import for example these:

import triqs.utility.mpi as mpi
from triqs_cthyb import solver

I get the error message above. 
I tried to find solutions on the internet, but so far nothing was helpful.
Do you know this issue and know how I can fix it?

I would be grateful for any hint!

Best regards,

Karla Baumann

I attach the CmakeCache.txt files in https://gist.github.com/karlabaumann/e40b34a229eaa25703a83e338b0b6261#file-cmakecache_cthyb

(just in case it doesn't work i put a zip folder with the files
[CMakeCache_folder.zip](https://github.com/TRIQS/cthyb/files/5958790/CMakeCache_folder.zip)

**Comment by Wentzell** [comment]
Dear @karlabaumann,

I assume you will see the same error message if you import mpi4py?

```
/shared/apps/python/3.9.1/bin/python3 -c "import mpi4py"
```

**Comment by karlabaumann** [comment]
Dear Nils Wentzell,

thank you very much for your very fast reply!
If I imported it correctly then yes unfortunately I get the same error 
message.

Best regards,
Karla Baumann




Le 2021-02-10 15:32, Nils Wentzell a écrit :
> Dear @karlabaumann,
> 
> I assume you will see the same error message if you import mpi4py?
> 
> ```
> /shared/apps/python/3.9.1/bin/python3 -c "import mpi4py"
> ```

**Comment by Wentzell** [comment]
There seems to be a problem with your MPI setup and/or environment.
A first guess would be that the issue occurs only on the login node of the cluster which may have limited MPI support?
Please contact your administrators and provide the information about "mpi4py".
They should be able to help you out.

Best,

Nils
