### ISSUE TITLE
Miscellaneous questions/feature requests

### ISSUE THREAD

**Issue by ec147** [TRIQS/cthyb#171]
Hi,

Just some quick questions about TRIQS/CT-HYB:

- I assume that by default a Monte-Carlo run starts from a configuration where all the orbitals are empty (?). Is there a way to start a Monte-Carlo run from a given configuration ? I am doing self-consistent run and thermalization is taking me a really long time, so this would help massively if I could start from a configuration of a previous iteration.
- When the density matrix is measured, is the time translation invariance taken into account ? Meaning, do you look only the configuration at time beta, or do you average over the whole segment [0,beta] ?  The density matrix is very important for me to get a clean energy.
- Do you plan on releasing an improved estimator any time soon (ideally in the rotationally invariant picture and Legendre basis) ?

Again, all of this would help me massively. All of these issues are really impeding my work.

Thanks

**Comment by the-hampel** [comment]
Hi @ec147,

> Do you plan on releasing an improved estimator any time soon (ideally in the rotationally invariant picture and Legendre basis) ?

Right now there is no concrete plan to implement improved estimators in triqs/cthyb. In case you are only interested in improved self-energies consider taking a look at: https://arxiv.org/abs/2310.01266 . Here, we showed how to leverage DLR + plus the measurement of high frequency moments: https://triqs.github.io/cthyb/latest/guide/high_freq_moments.html to achieve better noise suppression than standard improved estimators and the same noise level as symmetric improved estimators. I am currently working on a release version of the functionality within triqs for this, and I am happy to share a beta version of it. For the symmetric improved estimators we would require first a worm sampling algo in cthyb. 

> I assume that by default a Monte-Carlo run starts from a configuration where all the orbitals are empty (?). Is there a way to start a Monte-Carlo run from a given configuration ? I am doing self-consistent run and thermalization is taking me a really long time, so this would help massively if I could start from a configuration of a previous iteration.

As far as I know there is no way to initialize the startup configuration in MC right now and it is empty in the beginning 

@Wentzell @parcollet please correct me if I am wrong. Maybe you can also answer the second question regarding the density matrix. 

Best,
Alex

P.S. these questions are more qualified for a discussion. So far I do not see any obvious issue. So please consider next time to open this in a discussion instead.
