### ISSUE TITLE
Unknown CMake command "triqs_cython_module".

### ISSUE THREAD

**Issue by Bert-Tijskens** [TRIQS/cthyb#22]
hi just managed to build TRIQS 1.2 on our cluster,
as one of our users requests cthyb_matrix I checked it out and ran cmake.
Unknown CMake command "triqs_cython_module".
cmake -DTRIQS_PATH=$EBROOTTRIQS  ../cthyb_matrix
-- TRIQS : Adding compilation flags detected by the library (C++11/14, libc++, etc...) 
CMake Error at python/CMakeLists.txt:8 (triqs_cython_module):
  Unknown CMake command "triqs_cython_module".

-- Configuring incomplete, errors occurred!
See also "*********************/scratch/triqs-1.2/build/CMakeFiles/CMakeOutput.log".

this is mentioned in issue #4 
any help welcome
does git master branch correspond to version 1.2?

**Comment by pseth** [comment]
cthyb_matrix is compatible only up to v1.0. Try using cthyb instead, it is an improved version of cthyb_matrix.

**Comment by krivenko** [comment]
I think, CMake scripts of the applications must perform a library version check.

**Comment by Bert-Tijskens** [comment]
many thanks
On 22 Jan 2015, at 15:25, Priyanka Seth <notifications@github.com<mailto:notifications@github.com>> wrote:


cthyb_matrix is compatible only up to v1.0. Try using cthyb instead, it is an improved version of cthyb_matrix.

—
Reply to this email directly or view it on GitHub<https://github.com/TRIQS/cthyb/issues/22#issuecomment-71027262>.

Dr [Engel]bert Tijskens
HPC Analyst/Consultant

Flemish Supercomputer Center vscentrum.be<http://vscentrum.be>
HPC core facility CalcUA uantwerp.be/calcua<http://uantwerp.be/calcua>
Computational mathematics www.uantwerpen.be/en/rg/cma

University of Antwerp
Middelheimlaan1 G.309, B-2020 Antwerp, Belgium

engelbert.tijskens@uantwerpen.be
++32 3 265 3879

**Comment by parcollet** [comment]
@krivenko : yes, we have to do it....

**Comment by krivenko** [comment]
Can we close this issue as solved by 9a281e797be6a00025ef6dc466d39d27404adc66?

**Comment by pseth** [comment]
Yes.
