### ISSUE TITLE
Test 3 (anderson) takes forever

### ISSUE THREAD

**Issue by mzingl** [TRIQS/cthyb#23]
I installed the newest version of the TRIQS library and the newest cthyb solver. Installation works,however the anderson test (nr 3) starts, but terminates after 600 sec. 

This is the output in anderson_output:
Welcome to the CTHYB solver
The local Hamiltonian of the problem:
-1*C^+(tot,0)C(tot,0) + -1*C^+(tot,1)C(tot,1) + 2*C^+(tot,0)C^+(tot,1)C(tot,1)C(tot,0)
Using autopartition algorithm to partition the local Hilbert space
Found 4 subspaces.
 
1%; 2%;

anderson_output.err is empty.
And no it is not my computer - I tried it on another machine. ;)

**Comment by pseth** [comment]
Oops, my fault, I forgot to uncomment a macro that I had switched on for debugging.. Fixed. Can you confirm that it works now?

**Comment by mzingl** [comment]
Thanks, it works fine again!
