### ISSUE TITLE
Solve changes S.G0_iw

### ISSUE THREAD

**Issue by pseth** [TRIQS/cthyb#24]
I was caught by some unexpected though explained behaviour of the solve method. In trying to accumulate some statistics on a converged calculation, I noticed that S.G0_iw was slightly different at each measurement.

In the script below, G0_iw before the solve and after are different as the 1/iw behaviour is changed in the solve routine, see solver_core.cpp around line 121.
```
S.G0_iw << S.Sigma_iw + inverse(S.G_iw)
S.G0_iw << inverse(S.G0_iw)
ar = HDFArchive('testfile.h5','a')
ar['G0_iw-orig'] = S.G0_iw
del ar

# Start DMFT iterations:
for iteration_number in range(1,loops+1):
    ar = HDFArchive('testfile.h5','a')
    ar['G0_iw-before-%s'%(iteration_number)] = S.G0_iw
    del ar

    p["random_seed"] = 34788 + 928374*mpi.rank + iteration_number + previous_runs
    # Solve the impurity problem:
    S.solve(h_loc=h_loc, **p)

    # Write the final Sigma and G to the hdf5 archive:
    ar = HDFArchive('testfile.h5','a')
    ar['G0_iw-after-%s'%(iteration_number)] = S.G0_iw
    ar['G_tau-%s'%(iteration_number)] = S.G_tau
    del ar
```

Do we want to correct the 1/iw behaviour in G0_iw? I did this as it was what was done in the previous solver, but I am not sure it is necessary or good. The user probably expects the input to not change.

**Comment by krivenko** [comment]
I would vote for not touching `G0_iw` inside `solve()`.
If `G0_iw` provided by the user has wrong asymptotics, this is an error, which must be either reported or ignored. Making a silent correction to the function may easily catch the user by surprise.

**Comment by pseth** [comment]
Ok, printing a warning in python interface for Solver, for "novice" users, but not changing G0. I assume that expert users will not want such a message.
