### ISSUE TITLE
Make warning os OS X

### ISSUE THREAD

**Issue by Titan-C** [TRIQS/cthyb#26]
while performing an install cmake complains
```
$cmake -DTRIQS_PATH=/home/oscar/libs/ ../cthyb/
-- The CXX compiler identification is GNU 4.9.2
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- TRIQS : Adding compilation flags detected by the library (C++11/14, libc++, etc...) 
-- Found TRIQS: /home/oscar/libs/lib/libtriqs.so  
-- Hash: d275c6453168e90ddbf7b88cef977b4e35fab5be
-- Preparing extension module cthyb
-- Configuring done
CMake Warning (dev) at /home/oscar/libs/share/triqs/cmake/TRIQSConfig.cmake:111 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "/home/oscar/dev/buicthyb/python/cthyb_desc.py" of
  target "python_wrap_cthyb" does not exist.
Call Stack (most recent call first):
  python/CMakeLists.txt:12 (triqs_python_extension)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/oscar/dev/buicthyb
```
but it finishes. Nevertheless make is not able to find the include dir either
```
$make
Scanning dependencies of target cthyb_c
[  4%] Building CXX object c++/CMakeFiles/cthyb_c.dir/solver_core.cpp.o
In file included from /home/oscar/dev/cthyb/c++/solver_core.cpp:21:0:
/home/oscar/dev/cthyb/c++/./solver_core.hpp:22:30: fatal error: triqs/mc_tools.hpp: No such file or directory
 #include <triqs/mc_tools.hpp>
                              ^
compilation terminated.
c++/CMakeFiles/cthyb_c.dir/build.make:54: recipe for target 'c++/CMakeFiles/cthyb_c.dir/solver_core.cpp.o' failed
make[2]: *** [c++/CMakeFiles/cthyb_c.dir/solver_core.cpp.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'c++/CMakeFiles/cthyb_c.dir/all' failed
make[1]: *** [c++/CMakeFiles/cthyb_c.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by pseth** [comment]
Are you still having this problem?

**Comment by Titan-C** [comment]
Based on current master
The warning of cmake that target "python_wrap_cthyb" does not exist is still there but I can build and pass the tests

**Comment by parcollet** [comment]
yes, there are these warnings in Os X. 
Never had time to look into them and fix them ... 
Probably because OS X is using a more recent cmake version.

**Comment by krivenko** [comment]
I can see this warning on many Linux machines too. By the way, the warning is about a missing **dependency** of `python_wrap_cthyb`, not about the target itself.

Here is the statement in `TRIQSConfig.cmake.in` (line 117) responsible for the message:
```
add_dependencies(python_wrap_${ModuleName} py_copy {CMAKE_CURRENT_BINARY_DIR}/${ModuleName}_desc.py )
```
`add_dependencies` expects all its arguments to be targets, while a file name is passed.

**Comment by parcollet** [comment]
Ok, can we clean this ? I guess we need an add_custom_target ??

**Comment by krivenko** [comment]
My solution: TRIQS/triqs@2e2408d1fc33e23d47bd4cb821e699cd05ed5500
Reshuffled some arguments of `add_custom_command`, `add_custom_target` and `add_dependencies`.

**Comment by krivenko** [comment]
Still open?

**Comment by pseth** [comment]
Does Igor's commit resolve your issue, @Titan-C?

**Comment by Titan-C** [comment]
Sorry, I'm not sure. I just updated from triqs master to test but first it fails 5 tests
```
The following tests FAILED:
        134 - fourier_tensor (Not Run)
        154 - issue274 (Not Run)
        155 - issue274_np2 (Failed)
        156 - issue274_np3 (Failed)
        157 - issue274_np4 (Failed)
```
Ignoring that I did a `make install` and it also fails with
```
[ 88%] Linking CXX executable fourier_tensor
/home/oscar/miniconda3/envs/hpc2/lib/python2.7/config/libpython2.7.a(posixmodule.o): In function `posix_tmpnam':
-------src-dir-------/Python-2.7.11/./Modules/posixmodule.c:7631: warning: the use of `tmpnam_r' is dangerous, better use `mkstemp'
/home/oscar/miniconda3/envs/hpc2/lib/python2.7/config/libpython2.7.a(posixmodule.o): In function `posix_tempnam':
-------src-dir-------/Python-2.7.11/./Modules/posixmodule.c:7578: warning: the use of `tempnam' is dangerous, better use `mkstemp'
CMakeFiles/fourier_tensor.dir/fourier_tensor.cpp.o: In function `Fourier_Tensor_valued_Test::TestBody()':
fourier_tensor.cpp:(.text+0xd90): undefined reference to `triqs::gfs::fourier(triqs::gfs::gf_const_view<triqs::gfs::imtime, triqs::gfs::tensor_valued<3>, triqs::gfs::nothing, void>, triqs::arrays::array_view<triqs::gfs::tail, 3, void, false, true>, int)'
collect2: error: ld returned 1 exit status
test/triqs/gfs/functions/CMakeFiles/fourier_tensor.dir/build.make:149: recipe for target 'test/triqs/gfs/functions/fourier_tensor' failed
make[2]: *** [test/triqs/gfs/functions/fourier_tensor] Error 1
CMakeFiles/Makefile2:6832: recipe for target 'test/triqs/gfs/functions/CMakeFiles/fourier_tensor.dir/all' failed
make[1]: *** [test/triqs/gfs/functions/CMakeFiles/fourier_tensor.dir/all] Error 2
Makefile:160: recipe for target
```

**Comment by JATIN199604** [comment]
Dear TRIQS developer. I will use TRIQS as an interface to WIEN2k. I am getting error during make. can you say how it can be solved . 
jatin@jatin-HP-Laptop-14s-cr1xxx:~/DMFT/triqs.build$ make
[  1%] Built target cpp2py
[  2%] Built target gtest
[  3%] Linking CXX shared library libtriqs.so
/usr/bin/ld: /usr/local/lib/libfftw3.a(assert.o): relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
triqs/CMakeFiles/triqs.dir/build.make:1044: recipe for target 'triqs/libtriqs.so' failed
make[2]: *** [triqs/libtriqs.so] Error 1
CMakeFiles/Makefile2:339: recipe for target 'triqs/CMakeFiles/triqs.dir/all' failed
make[1]: *** [triqs/CMakeFiles/triqs.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Wentzell** [comment]
@JATIN199604 

It is enough to post your problem once .. please **DO NOT** repost the same issue multiple times and wait for us to get back to you ...
