### ISSUE TITLE
Almost all tests fail after update

### ISSUE THREAD

**Issue by opeil** [TRIQS/cthyb#27]
I have pulled the latest version of the solver (d275c645) recompiled it and run tests. Practically all tests failed because of the difference in the output h5-files. For one of the tests (anderson) I checked the content of the output.h5 and the data of Gtot turned out to be just a zero array.

Is there anything extra I can check to identify the problem?

The following tests FAILED:
	  3 - anderson (Failed)
	  4 - anderson_block (Failed)
	  5 - anderson_qn (Failed)
	  6 - anderson_block_qn (Failed)
	  7 - spinless (Failed)
	  8 - spinless_qn (Failed)
	  9 - kanamori (Failed)
	 10 - kanamori_qn (Failed)
	 11 - kanamori_offdiag (Failed)
	 12 - kanamori_offdiag_qn (Failed)
	 13 - legendre (Failed)
	 15 - kanamori (Failed)
	 16 - single_site_bethe (Failed)
	 17 - slater (Failed)

**Comment by pseth** [comment]
That's odd -- I just recompiled, and my tests run without any problems. Can you try a clean install from an empty build directory?

**Comment by opeil** [comment]
Tried a clean install (only of cthyb) -- same result. This time I checked test 'kanamori' and found the same thing: arrays are empty (zero-valued).
Here is a log output:


9/17 Testing: kanamori
9/17 Test: kanamori
Command: "/usr/bin/cmake" "-Dname=kanamori" "-Dcmd=/home/opeil/Codes/triqs/triqs1.2/applications/cthyb/build_new/test/c++/kanamori" "-DoutputName=kanamori.output.h5" "-Dreference=/home/opeil/Codes/triqs/triqs1.2/applications/cthyb/src/test/c++/kanamori.output.h5" "-DH5_DIFF_EXECUTABLE=/cm/shared/apps/python-anaconda/2.7.8/bin/h5diff" "-DH5_DIFF_OPTIONS= -d 1.e-5" "-DH5_DIFF_OBJECTS=" "-P" "/home/opeil/Codes/triqs/triqs1.2/install/share/triqs/cmake/run_test.cmake"
Directory: /home/opeil/Codes/triqs/triqs1.2/applications/cthyb/build_new/test/c++
"kanamori" start time: Apr 01 20:07 CEST
Output:
----------------------------------------------------------
 command for the test /home/opeil/Codes/triqs/triqs1.2/applications/cthyb/build_new/test/c++/kanamori
About to compare with /cm/shared/apps/python-anaconda/2.7.8/bin/h5diff -d 1.e-5 kanamori.output.h5 /home/opeil/Codes/triqs/triqs1.2/applications/cthyb/src/test/c++/kanamori.output.h5
CMake Error at /home/opeil/Codes/triqs/triqs1.2/install/share/triqs/cmake/run_test.cmake:62 (message):
  output does not match for 'kanamori': ; dataset: </G_down-0/data> and
  </G_down-0/data>

  2488 differences found

  dataset: </G_down-0/singularity/data> and </G_down-0/singularity/data>

  1 differences found

  dataset: </G_down-1/data> and </G_down-1/data>

  2494 differences found

  dataset: </G_down-1/singularity/data> and </G_down-1/singularity/data>

  1 differences found

  dataset: </G_up-0/data> and </G_up-0/data>

  2491 differences found

  dataset: </G_up-0/singularity/data> and </G_up-0/singularity/data>

  1 differences found

  dataset: </G_up-1/data> and </G_up-1/data>

  2498 differences found

  dataset: </G_up-1/singularity/data> and </G_up-1/singularity/data>

  1 differences found

  ; shell output: 1!


<end of output>

**Comment by pseth** [comment]
Maybe the install didn't work? Also, did you run the tests before or after the make install? Could you pull the latest version of triqs and cthyb (which you have already) and do a clean install again? Try running the tests *after* `make install`.

**Comment by opeil** [comment]
I did not do install, that's right, because I don't want to break the current working version. But now I vaguely remember that in this cases the tests might not work. So, I will try to do a separate clean build and install to check if this works.

**Comment by opeil** [comment]
Clean build and install works. The issue was probably in the order of install/test (which is is far from logical).
