### ISSUE TITLE
QUANTUM ESPRESSO + TRIQS

### ISSUE THREAD

**Issue by EBRUDU1** [TRIQS/cthyb#29]
After months of struggling with the installation of the TRIQS I finally got it running.
I observed that there are a few omissions in the example.py file:
"import matplotlib
matplotlib.pyplot.show()"
It was only after appending the above two lines of code that example.py produced a graph.

In the LDA+DMFT Wien2k was used  as model which would have been alright for everybody if Wien2k was a free software, but as it is not free. Hence TRIQS would fill a really big void for condensed matter physics community if a freely available software like QUANTUM ESPRESSO can be used to show how DFT is incorporated into TRIQS.
I know it is a lot of sacrifice but there is need for it.

**Comment by pseth** [comment]
Thank you for the comment, it has been considered and is now on the future request list.
