### ISSUE TITLE
plots in doc

### ISSUE THREAD

**Issue by pseth** [TRIQS/cthyb#30]
Currently the plots in the doc are not working due to some sphinx issue with the `.. plot` command. I believe Olivier looked at this and knows where the problem lies. I am putting it up here before I forget of the existence of this problem!

**Comment by krivenko** [comment]
This is a more general issue of the Sphinx setup in TRIQS: TRIQS/triqs#236

**Comment by krivenko** [comment]
Fixed in a3b2aab9a18213343ca2a5b798e457f31a7ae069, requires testing...

**Comment by pseth** [comment]
It looks like it is working now, closing.
