### ISSUE TITLE
cthyb error: unrecognized parameres

### ISSUE THREAD

**Issue by leopo** [TRIQS/cthyb#31]
I compiled the current version of cthyb, and now I get the following error while trying to run a script:

Traceback (most recent call last):
  File "Fe-hcp.py", line 119, in <module>
    S.solve(h_loc=Hloc, **p)
  File "/home/x_leopo/TRIQS1.2/install/lib/python2.7/site-packages/pytriqs/applications/impurity_solvers/cthyb/cthyb_solver.py", line 90, in solve
    SolverCore.solve(self, h_loc = h_loc, **params_kw)
TypeError:
---- There are 2 errors in Python -> C++ transcription for the class solve_parameters_t

1 The parameter 'fit_min_n' is not recognized.
2 The parameter 'fit_max_n' is not recognized.

This script was passing fine about a month ago. There I put these tail fitting parameters into p dict:
p["fit_min_n"] = fit_start
p["fit_max_n"] = fit_start+fit_interval

and **p is then passed to S.Solve

**Comment by pseth** [comment]
You need to add the switch perform_tail_fit:
``p["perform_tail_fit"] = True``. As several people wanted to be able to save G_iw and Sigma_iw with and without tails, I added the switch to allow for this.

**Comment by leopo** [comment]
OK, thanks
