### ISSUE TITLE
solvercore error

### ISSUE THREAD

**Issue by Soumeniisc** [TRIQS/cthyb#33]
Hi!
I have faced following error in most recent CTHYB(downloaded 5 days back). Same input file is working fine with the previous one.

S.solve(h_loc=h_loc, **p)
  File "/home/soumen/INSTALLPACKAGES/15_05_15/lib/python2.7/dist-packages/pytriqs

/applications/impurity_solvers/cthyb/cthyb_solver.py", line 90, in solve
    SolverCore.solve(self, h_loc = h_loc, **params_kw)
TypeError: 
---- There are 3 errors in Python -> C++ transcription for the class solve_parameters_t

1 The parameter 'fit_min_n' is not recognized.
2 The parameter 'fit_n_moments' is not recognized.
3 The parameter 'fit_max_n' is not recognized.

Thnaks,

**Comment by pseth** [comment]
This is the same problem as #31 -- see the response there.

**Comment by Soumeniisc** [comment]
thanks
