### ISSUE TITLE
No 1.2 tag

### ISSUE THREAD

**Issue by aichhorn** [TRIQS/cthyb#35]
There is no 1.2 tag in the cthyb tree. Since there were things moved around quite a lot, the cthyb HEAD does not compile with the tagged TRIQS 1.2 version. Can we add a 1.2 tag for CTHYB that is consistent with TRIQS 1.2? Otherwise it is difficult to maintain a stable productive version for calculations.

**Comment by krivenko** [comment]
Hi Markus,
I have added a tag `1.2` to a commit, which should still be compilable with TRIQS 1.2.
Please try it now.

**Comment by aichhorn** [comment]
Thanks Igor, works for me!
