### ISSUE TITLE
Online docs should be rebuilt with a new cmake option

### ISSUE THREAD

**Issue by krivenko** [TRIQS/cthyb#36]
Hello,

In commit 58c4bcdd7383ee3e2cd917dd7e90285fcf121e8d I added a new (advanced) cmake option `TRIQS_INVENTORY_DIR` set to `${TRIQS_PATH}/share/doc/triqs` by default.

This option tells Sphinx where it should look for an inventory file needed to generate external references to the library docs. According to the default value, these references will point at the locally installed TRIQS docs.
However, one has to give an explicit URL, if the docs are built for a web-site:
```
-DTRIQS_INVENTORY_DIR=http://ipht.cea.fr/triqs/1.2/
```
implying `http://ipht.cea.fr/triqs/1.2/objects.inv` is the correct Sphinx inventory file.

**Comment by krivenko** [comment]
Are you going to create a new documentation subdir (1.3) on the website?
This one must not be hard to fix along the way...

**Comment by pseth** [comment]
Sure we should. Can you take care of this, I think you are more familiar with the sphinx setup?

**Comment by krivenko** [comment]
This is to be done by someone having access to Jenkins on `http://ipht.cea.fr/`...

**Comment by pseth** [comment]
@parcollet then?

**Comment by parcollet** [comment]
Ok, what shall I do ?

**Comment by krivenko** [comment]
@parcollet 
Simply add `-DTRIQS_INVENTORY_DIR=http://ipht.cea.fr/triqs/1.x/` to the CMake invocation line of cthyb.

**Comment by parcollet** [comment]
Done in Jenkins for cthyb, dfttools.
