### ISSUE TITLE
Running segment picture calculation

### ISSUE THREAD

**Issue by johanjoensson** [TRIQS/cthyb#40]
Hello!

If I want to run a DMFT calculation using the CTHYB segment picture solver, what do I need to do to when I instantiate the solver class?

Regards
Johan Jönsson

**Comment by pseth** [comment]
Hi Johan (cc @tayral),

The CTHYB code here is based on the matrix formulation, and does not include the segment picture optimizations for n-n interactions. The segment picture code (a separate package) is not publicly available at the moment.

Cheers,
Pri
