### ISSUE TITLE
TRIQS_HDF5_data_scheme AtomicDiagonalization is not recognized

### ISSUE THREAD

**Issue by krivenko** [TRIQS/cthyb#41]
Hello,

I get this error message
```
Warning : The TRIQS_HDF5_data_scheme AtomicDiagonalization is not recognized. Returning as a group. Hint : did you forgot to import this python class ?
```
when I try to load an `AtomicDiag` object from an archive. The Python class is imported as requested,
```python
from pytriqs.applications.impurity_solvers.cthyb import AtomDiag
```
Is this because the data scheme name does not match the Python class name?

**Comment by krivenko** [comment]
Comments anyone?

I checked the C++ source code of the Python wrapper, and found out that it calls `pytriqs.archive.hdf_archive_schemes.register_class()`.

`register_class(cls)` tries to extract the HDF5 scheme name from two sources,
* `cls._hdf5_data_scheme_`;
* `cls.__name__`, if the previous attempt failed.

Only the second option succeeds for `AtomDiag`, so the registered scheme is named `AtomDiag`.

What is important, the return value of `atom_diag::get_triqs_hdf5_data_scheme()` is never consulted. 
@parcollet @mferrero Is it a general issue of the library/wrapper generator?

**Comment by pseth** [comment]
I too have run into this problem now.
@parcollet @mferrero Can we please take a look at this asap?

@krivenko In the meantime, what can we do to get it working? Should we change the name of the data scheme?

**Comment by pseth** [comment]
Just spoke to Olivier. The decision is to restrict the HDF scheme name to be the same as the python name.

Fixing this in AtomDiag now.

**Comment by pseth** [comment]
Fixed.
