### ISSUE TITLE
Compilation problem on OS X

### ISSUE THREAD

**Issue by gsclauzero** [TRIQS/cthyb#42]
Hi,
    I am trying to compile cthyb on my Macbook (OSX 10.11.3) using Apple's LLVM plus Macport python2.7. I am trying to compile in C++11/14 mode in order to build the documentation. 

I did compile and deploy Triqs successfully, all tests were passed. The make configure of cthyb passes with a (unrelated?) warning message:
  Syntax Warning in cmake code at
    /Users/gabriele/Software/Triqs/Install/1.4dev/share/triqs/cmake/TRIQSConfig.cmake:41:168
  Argument not separated from preceding token by whitespace.

However, when I try to make cthyb, I got this error:
...
[ 19%] Generating cthyb_desc.py, cthyb_wrap.cpp, ../include/pytriqs/converters/cthyb.hpp
Traceback (most recent call last):
  File "/Users/gabriele/Software/Triqs/Builds/cthyb-1.4dev/python/cthyb_desc.py", line 9, in <module>
    module.use_module('gf', 'triqs')
TypeError: use_module() takes exactly 2 arguments (3 given)
make[2]: *** [python/cthyb_desc.py] Error 1
make[2]: *** Deleting file `python/cthyb_desc.py'
make[1]: *** [python/CMakeFiles/cthyb.dir/all] Error 2
make: *** [all] Error 2

Any idea?

**Comment by pseth** [comment]
There were a few cmake changes made recently, to be sure this is not due to a version conflict, could you update the library and cthyb, and try a fresh build?

**Comment by gsclauzero** [comment]
I downloaded both triqs_lib and cthyb yesterday morning. git pull says that I am already up-to-date with both repos. I am on the master branch, these are the hashes from rev-parse:
triqs: dc787d07477c4ba91edad013e8639f3af0044ad7
cthyb: c745d8408332ee7783a38ee45683a0183cdd0034

**Comment by parcollet** [comment]
Hi, yes there has been an update of the install in the triqs + cthyb on monday.
The first warning is an OS X issue, you can ignore it (or use -Wno-dev as cmake recommends)
More later ...

**Comment by pseth** [comment]
I just reinstalled my packages on the master branch and everything goes through..

@parcollet : Jenkins doesn't report this?

**Comment by parcollet** [comment]
Jenkins is fine.
Cf : https://triqs.ipht.cnrs.fr/jenkins/

**Comment by gsclauzero** [comment]
One question: is the file cthyb_desc.py generated during configure or make through c++2py.py, or is it used as it is from the repo?
Inside the wrap_generator.py that I get after installing TRIQS, the use_module method seems to take one argument,
def use_module(self, modulename) :
while in cthyb_desc.py it is called with two arguments,
module.use_module('gf', 'triqs')
There's surely something I don't understand.

**Comment by parcollet** [comment]
It is taken from the repository.
It is generated by the developers and put in the sources, since it generation require clang compiler.

**Comment by parcollet** [comment]
PS : again, this is the same change of last monday ... 
@tayral: we have trouble with this change ...

**Comment by gsclauzero** [comment]
Now everything goes through.
I do not understand if this was solved by a recent commit in triqs. 
The only thing I have changed in my setup is the addition of the clang module to python2.7
Now the wrap_generator.py looks better, i.e.:
   def use_module(self, modulename, app_name=None) :

**Comment by parcollet** [comment]
unrelated to this module. Maybe you did a full rebuild.
Anyway, if it is ok, I am closing this.
