### ISSUE TITLE
Make error on ubuntu14.04

### ISSUE THREAD

**Issue by henhans** [TRIQS/cthyb#43]
Dear TRIQS team,

I try to install the cthyb on my desktop, but it shows the following error:

Scanning dependencies of target cthyb_c
[  4%] Building CXX object c++/CMakeFiles/cthyb_c.dir/solver_core.cpp.o
[  8%] Building CXX object c++/CMakeFiles/cthyb_c.dir/atom_diag.cpp.o
[ 13%] Building CXX object c++/CMakeFiles/cthyb_c.dir/atom_diag_functions.cpp.o
[ 17%] Building CXX object c++/CMakeFiles/cthyb_c.dir/atom_diag_worker.cpp.o
[ 21%] Building CXX object c++/CMakeFiles/cthyb_c.dir/impurity_trace.cpp.o
[ 26%] Building CXX object c++/CMakeFiles/cthyb_c.dir/measure_density_matrix.cpp.o
Linking CXX shared library libcthyb_c.so
[ 26%] Built target cthyb_c
[ 30%] Generating cthyb/cthyb_wrap.cpp, ../include/cthyb/py_converters/cthyb.hpp
/usr/bin/python: can't open file '/home/thlee/library/cthyb/build/python/cthyb/cthyb_desc.py': [Errno 2] No such file or directory
make[2]: *** [python/cthyb/cthyb_wrap.cpp] Error 2
make[1]: *** [python/CMakeFiles/cthyb.dir/all] Error 2
make: *** [all] Error 2

I'm able to install cthyb on my laptop, and I compare the difference between my laptop and desktop. I found that there's no such directory "/build/python/cthyb/" on my laptop(which I successfully installed cthyb). Also, there's a file "sitecustomize.py" on my laptop in the build top directory, but there's no such file on my desktop. I'm wondering how should I solve this problem?

Thank you.
Tsung-Han

**Comment by parcollet** [comment]
Hi, there has been a little change in the installation system on monday on the master branch.
(in particular, the sitecustomize.py file was moved to /python ...).
Can you:
- update (git pull) both the library (TRIQS) and CTHYB 
- make a clean build for both.
It works on our machines here.

**Comment by henhans** [comment]
Dear Dr. Parcollet,
Thank you very much! It works now. But it seems the cthyb.so did not successfully install to /usr/lib/python2.7/dist-packages/applications/impurity_solvers/cthyb/.  Instead, it goes to /usr/lib/python2.7/dist-packages/cthyb/cthyb.so. I need to copy the cthyb.so file to the former directory in order to import to python script.
Thank you.
Tsung-Han

**Comment by parcollet** [comment]
Thanks for reporting this, it is not normal ...
@tayral To be fixed.
