### ISSUE TITLE
partition_method = "none" does not work

### ISSUE THREAD

**Issue by krivenko** [TRIQS/cthyb#44]
`cthyb` throws an exception when I try to set the partition method to `none`.
```
Traceback (most recent call last):
  File "spin_mixing.py", line 60, in <module>
    S.solve(h_int=H, **p)
RuntimeError: .. Error occurred at Tue Feb  9 15:04:41 2016

.. Error .. calling C++ overload 
.. solve() -> void 
.. in implementation of method SolverCore.solve
.. C++ error was : 
.. Triqs runtime error at /home/igor/Physics/TRIQS/cthyb.git/c++/atom_diag_worker.cpp : 361

The bare vacuum is not in a block of size 1 !
.. Error occurred on node 0
```
Is there a good reason for this restriction? It implies that the total number of particles is a quantum number of `h_loc`, which is not necessarily the case.

**Comment by pseth** [comment]
That is true. We could remove the restriction and put a warning in instead, something like 'The bare vacuum is not in a block of size 1, proceed only if you are sure this is correct!'

What do you think?

**Comment by krivenko** [comment]
I am not sure I understand the entire need of this check, no matter if it leads to an error or to a warning...

**Comment by aichhorn** [comment]
From a physics point of view, I would say that 1) if you care about block structure, then the vacuum must be a block of size one, and the exception is fine, but 2) if you don't care about blocks, the whole test has no meaning. Agree?

**Comment by krivenko** [comment]
> From a physics point of view, I would say that 1) if you care about block structure, then the vacuum must be a block of size one

Must it? I was hit by this issue while trying to add anomalous terms to the local Hamiltonian,`c_dag('up',0)*c_dag('dn',0) - c('up',0)*c('dn',0)`.

**Comment by aichhorn** [comment]
Oh, I see. I realize that I was wrong with my statement. I was arguing with the number of vacuum states (which is one), but that does not necessarily imply something for the block structure of the hamiltonian, which we are discussing here. As soon as the Hamiltonian does not conserve the particle number, then the ordinary Fock vacuum state with zero particles of course is in a larger block of the hamiltonian. Igor, I agree, I don't see a point in testing if the hamiltonian block containing the |0> state is of size one.

**Comment by pseth** [comment]
I guess the check was put there during development, when we weren't thinking of these cases. Perhaps the best thing is to check the diagonalisation a case in which N is not a good quantum number for a h_loc with known eigenstates, and remove the error. This check should also go into the cthyb tests (and will be moved to triqs with atom_diag).

**Comment by krivenko** [comment]
> Perhaps the best thing is to check the diagonalisation a case in which N is not a good quantum number for a h_loc with known eigenstates, and remove the error.

Ok, I shall prepare such a test.
When do you plan to upgrade the diagonalization part to the library, before 1.4 is released or after?

**Comment by pseth** [comment]
The plan is to upgrade it for the 1.4 release. For the moment, I would say that the test can go in cthyb, but with a name atom_diag_something, to make it clear it is related, or even in the existing atom_diag test.
