### ISSUE TITLE
Compile problem in the master branch using complex options

### ISSUE THREAD

**Issue by PhyMinjaeKim** [TRIQS/cthyb#48]
I got error messages when I tried to compile CTHYB in the master branch with options, 
Complex interaction-ON, Complex hybridization-ON.

When I tried to compile CTHYB without complex options, there was no problem.

Please check following information.

* git hash for cthyb
3c18353c38cfd5ef2daf19a929e8c35c725681e5

* git has for triqs
416eb258dbdc39b5736e8633da5289aafe3a8147

* error message

-- Hash: 3c18353c38cfd5ef2daf19a929e8c35c725681e5
-- TRIQS : Adding compilation flags detected by the library (C++11/14, libc++, etc...)
-- Preparing extension module cthyb
-- Configuring done
-- Generating done
-- Build files have been written to: /home/minjae/METHODS/TRIQS/cthyb/build
Scanning dependencies of target py_copy
[  4%] Generating py_copy.tar
[  4%] Built target py_copy
Scanning dependencies of target cthyb_c
[ 17%] [ 17%] [ 17%] Building CXX object c++/CMakeFiles/cthyb_c.dir/atom_diag.cpp.o
[ 26%] [ 26%] Building CXX object c++/CMakeFiles/cthyb_c.dir/atom_diag_functions.cpp.o
Building CXX object c++/CMakeFiles/cthyb_c.dir/solver_core.cpp.o
[ 30%] Building CXX object c++/CMakeFiles/cthyb_c.dir/impurity_trace.cpp.o
Building CXX object c++/CMakeFiles/cthyb_c.dir/atom_diag_worker.cpp.o
Building CXX object c++/CMakeFiles/cthyb_c.dir/measure_density_matrix.cpp.o
Linking CXX static library libcthyb_c.a
[ 30%] Built target cthyb_c
Scanning dependencies of target h_diag_test
Scanning dependencies of target anderson_block_qn
Scanning dependencies of target kanamori
Scanning dependencies of target anderson
Scanning dependencies of target anderson_qn
Scanning dependencies of target anderson_block
Scanning dependencies of target atomic_gf
Scanning dependencies of target cthyb
[ 34%] Building CXX object test/c++/CMakeFiles/h_diag_test.dir/h_diag_test.cpp.o
[ 60%] [ 47%] [ 60%] [ 60%] [ 60%] [ 60%] [ 65%] Building CXX object test/c++/CMakeFiles/anderson_block_qn.dir/anderson.cpp.o
Building CXX object test/c++/CMakeFiles/kanamori.dir/kanamori.cpp.o
Building CXX object test/c++/CMakeFiles/anderson.dir/anderson.cpp.o
Building CXX object test/c++/CMakeFiles/anderson_qn.dir/anderson.cpp.o
Building CXX object test/c++/CMakeFiles/atomic_gf.dir/atomic_gf.cpp.o
Building CXX object test/c++/CMakeFiles/anderson_block.dir/anderson.cpp.o
Building CXX object python/CMakeFiles/cthyb.dir/cthyb/cthyb_wrap.cpp.o
/home/minjae/METHODS/TRIQS/cthyb/src/test/c++/h_diag_test.cpp: In function ‘int main()’:
/home/minjae/METHODS/TRIQS/cthyb/src/test/c++/h_diag_test.cpp:34:37: error: no matching function for call to ‘cthyb::atom_diag::atom_diag(triqs::operators::many_body_operator_generic<triqs::utility::real_or_complex>&, triqs::hilbert_space::fundamental_operator_set&, std::vector<triqs::operators::many_body_operator_generic<double> >&)’
    atom_diag h_diag(H, fops, qn_list);
                                     ^
/home/minjae/METHODS/TRIQS/cthyb/src/test/c++/h_diag_test.cpp:34:37: note: candidates are:
In file included from /home/minjae/METHODS/TRIQS/cthyb/src/test/c++/h_diag_test.cpp:2:0:
/home/minjae/METHODS/TRIQS/cthyb/src/c++/./atom_diag.hpp:45:2: note: cthyb::atom_diag::atom_diag(const many_body_op_t&, const triqs::hilbert_space::fundamental_operator_set&, const std::vector<triqs::operators::many_body_operator_generic<std::complex<double> > >&)
  atom_diag(many_body_op_t const& h_, fundamental_operator_set const& fops, std::vector<many_body_op_t> const& qn_vector);
  ^
/home/minjae/METHODS/TRIQS/cthyb/src/c++/./atom_diag.hpp:45:2: note:   no known conversion for argument 3 from ‘std::vector<triqs::operators::many_body_operator_generic<double> >’ to ‘const std::vector<triqs::operators::many_body_operator_generic<std::complex<double> > >&’
/home/minjae/METHODS/TRIQS/cthyb/src/c++/./atom_diag.hpp:44:2: note: cthyb::atom_diag::atom_diag(const many_body_op_t&, const triqs::hilbert_space::fundamental_operator_set&)
  atom_diag(many_body_op_t const& h_, fundamental_operator_set const& fops);
  ^
/home/minjae/METHODS/TRIQS/cthyb/src/c++/./atom_diag.hpp:44:2: note:   candidate expects 2 arguments, 3 provided
/home/minjae/METHODS/TRIQS/cthyb/src/c++/./atom_diag.hpp:43:22: note: cthyb::atom_diag::atom_diag()
  TRIQS_CPP2PY_IGNORE atom_diag() = default;
                      ^
/home/minjae/METHODS/TRIQS/cthyb/src/c++/./atom_diag.hpp:43:22: note:   candidate expects 0 arguments, 3 provided
/home/minjae/METHODS/TRIQS/cthyb/src/c++/./atom_diag.hpp:34:7: note: cthyb::atom_diag::atom_diag(const cthyb::atom_diag&)
 class atom_diag {
       ^
/home/minjae/METHODS/TRIQS/cthyb/src/c++/./atom_diag.hpp:34:7: note:   candidate expects 1 argument, 3 provided
/home/minjae/METHODS/TRIQS/cthyb/src/c++/./atom_diag.hpp:34:7: note: cthyb::atom_diag::atom_diag(cthyb::atom_diag&&)
/home/minjae/METHODS/TRIQS/cthyb/src/c++/./atom_diag.hpp:34:7: note:   candidate expects 1 argument, 3 provided
make[2]: *** [test/c++/CMakeFiles/h_diag_test.dir/h_diag_test.cpp.o] Error 1
make[1]: *** [test/c++/CMakeFiles/h_diag_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX executable anderson_block
[ 65%] Built target anderson_block
Linking CXX executable anderson
Linking CXX executable anderson_qn
Linking CXX executable anderson_block_qn
[ 65%] Built target anderson
Linking CXX executable atomic_gf
Linking CXX shared module cthyb/cthyb.so
[ 65%] Built target anderson_block_qn
[ 65%] Built target anderson_qn
Linking CXX executable kanamori
[ 69%] Built target cthyb
[ 69%] Built target atomic_gf
[ 69%] Built target kanamori
make: *** [all] Error 2

**Comment by gkraberger** [comment]
I am experiencing the same problem.
