### ISSUE TITLE
p not finite

### ISSUE THREAD

**Issue by pseth** [TRIQS/cthyb#5]
I run into a "p not finite" problem during a single band calculation at beta=5000. See the code that generates the error and the error message below.

https://gist.github.com/pseth/e03a67b9dda05e7224ef#file-gistfile1-txt

**Comment by pseth** [comment]
I will leave this issue open just for reference in the future, but the present conclusion is to leave this problem as is and address it if we encounter it in real (ie. not test) calculations down the road.

**Comment by parcollet** [comment]
Our conclusion was to add an exception if the det is 0, 
to have a clean error message. That is easy, and indeed, we will look at it if needed.

**Comment by parcollet** [comment]
@krivenko : what was the conclusion here ?
Was the issue solved by #282 or not ?

**Comment by krivenko** [comment]
@parcollet I'll have to rerun the script from the first message to make a conclusion...

**Comment by krivenko** [comment]
Ok, I checked that script once more, with both real and complex versions of the solver.
The results look reasonable and no crash whatsoever.
Finally, we can close this epic issue.
