### ISSUE TITLE
Not even c++ tests if TRIQS is compiled with PythonSupport=OFF

### ISSUE THREAD

**Issue by patrikthunstrom** [TRIQS/cthyb#52]
If I compile TRIQS with PythonSupport=OFF then the CMakeLists.txt skips the add_subdirectory(test), which then also excludes the c++ tests. 

Suggested fix:
Move the 
if (${Tests})
 add_subdirectory(test)
endif()
part out of the "if (${TRIQS_WITH_PYTHON_SUPPORT})" block in the CMakeLists.txt, and then replaced the "add_subdirectory(python)" line in tests/CMakeLists.txt with
if (${TRIQS_WITH_PYTHON_SUPPORT})
  add_subdirectory(python)
endif()

I tried this and it worked like a charm.
[...]$ make test
Running tests...
Test project [...]/triqs/solvers/cthyb/build
      Start  1: h_diag_test
 1/14 Test  #1: h_diag_test ......................   Passed    0.03 sec
      Start  2: rbt
 2/14 Test  #2: rbt ..............................   Passed    0.02 sec
      Start  3: anderson
 3/14 Test  #3: anderson .........................   Passed    0.72 sec
      Start  4: anderson_block
 4/14 Test  #4: anderson_block ...................   Passed    0.72 sec
      Start  5: anderson_qn
 5/14 Test  #5: anderson_qn ......................   Passed    0.56 sec
      Start  6: anderson_block_qn
 6/14 Test  #6: anderson_block_qn ................   Passed    0.71 sec
      Start  7: spinless
 7/14 Test  #7: spinless .........................   Passed    0.91 sec
      Start  8: spinless_qn
 8/14 Test  #8: spinless_qn ......................   Passed    0.91 sec
      Start  9: kanamori
 9/14 Test  #9: kanamori .........................   Passed    1.59 sec
      Start 10: kanamori_qn
10/14 Test #10: kanamori_qn ......................   Passed    2.04 sec
      Start 11: kanamori_offdiag
11/14 Test #11: kanamori_offdiag .................   Passed    1.16 sec
      Start 12: kanamori_offdiag_qn
12/14 Test #12: kanamori_offdiag_qn ..............   Passed    1.64 sec
      Start 13: legendre
13/14 Test #13: legendre .........................   Passed    0.82 sec
      Start 14: atomic_gf
14/14 Test #14: atomic_gf ........................   Passed    0.09 sec

100% tests passed, 0 tests failed out of 14

Total Test time (real) =  11.92 sec

**Comment by HugoStrand** [comment]
Hej Patrik!
Thanks for the bug report. I will fix this on the branch `unstable`.
Best, Hugo
