### ISSUE TITLE
Installation : Unknown CMake command "triqs_add_cpp_test"

### ISSUE THREAD

**Issue by francoisjamet** [TRIQS/cthyb#53]
Dear experts,

I'm trying to install cthyb (master) on Archlinux. 
But when I try the Cmake command:  
```
cmake -DTRIQS_PATH=../triqs_try/   ../cthyb.src
```

I get :
``` 
-- The CXX compiler identification is GNU 7.1.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found TRIQS: /home/jamet/triqs_try/lib/libtriqs.so  
-- Hash: dc089d586a0fdee0e98861cf404e0af7c54a014e
-- TRIQS : Adding compilation flags detected by the library (C++11/14, libc++, etc...) 
-- Preparing extension module cthyb
CMake Error at test/c++/CMakeLists.txt:2 (find_package):
  find_package Error reading CMake code from
  "../triqs_try/share/triqs/cmake/FindTriqsTest.cmake".


CMake Error at test/c++/CMakeLists.txt:16 (triqs_add_cpp_test):
  Unknown CMake command "triqs_add_cpp_test".
```
Everything works if I add ```-DTests=OFF```but it's not recommended, is it ?

PS: I could add that during the TRIQS compilation I got the following error in the make test: 
```
99% tests passed, 1 tests failed out of 198

Total Test time (real) =  37.63 sec

The following tests FAILED:
	171 - autocorrelation_jackknife (Failed)
Errors while running CTest
make: *** [Makefile:137: test] Error 8
```

But I did ```make install``` anyway.... Maybe it's related.

Thanks in advance !

**Comment by krivenko** [comment]
Dear Francois,

Could you try passing the absolute path (without using `../`) to your TRIQS installation as `TRIQS_PATH`?

**Comment by francoisjamet** [comment]
Dear Igor,

It works! thanks!

but why does the relative path  not work in this case?

**Comment by krivenko** [comment]
> but why does the relative path not work in this case?

Because it is evaluated with respect to different base directories at different points of our CMake scripts.
We could, in principle, convert relative paths to absolute ones in the very beginning. But then it's unclear (to me), what directory to use as a base.

**Comment by francoisjamet** [comment]
Ok thanks!
