### ISSUE TITLE
Solver crashes - complex version of CT-HYB

### ISSUE THREAD

**Issue by dmantadakis** [TRIQS/cthyb#54]
Dear All,

I have set a single-band Hubbard model, to run some tests with the complex version of CT-HYB, but I came up with the following error message:
`
.. Error .. calling C++ overload 
.. solve() -> void 
.. in implementation of method SolverCore.solve
.. C++ error was : 
.. Triqs runtime error at /home/mantadakis/Sources/TRIQS/master/triqs.install/include/triqs/mc_tools/./mc_move_set.hpp : 194

Monte Carlo Error : the rate ((nan,nan)) is not finite in move Shift one operator
.. Error occurred on node 0
`
Any ideas why?? Thanks!

**Comment by dmantadakis** [comment]
Update: I don't know if it really matters but when installing the CT-HYB I got the following warnings:

> Scanning dependencies of target cthyb_c
[  2%] Building CXX object c++/CMakeFiles/cthyb_c.dir/solver_core.cpp.o
In file included from /home/mantadakis/Sources/TRIQS/master/cthyb.src/c++/./qmc_data.hpp:22:0,
                 from /home/mantadakis/Sources/TRIQS/master/cthyb.src/c++/solver_core.cpp:22:
/home/mantadakis/Sources/TRIQS/master/cthyb.src/c++/./impurity_trace.hpp: In member function ‘void cthyb::impurity_trace::try_replace(const oplist_t&)’:
/home/mantadakis/Sources/TRIQS/master/cthyb.src/c++/./impurity_trace.hpp:401:62: warning: throw will always call terminate() [-Wterminate]
   if (!backup_nodes.is_index_reset()) TRIQS_RUNTIME_ERROR << "impurity_trace: improper use of try_replace()";
                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
and 

> [ 12%] Building CXX object c++/CMakeFiles/cthyb_c.dir/impurity_trace.cpp.o
In file included from /home/mantadakis/Sources/TRIQS/master/cthyb.src/c++/impurity_trace.cpp:21:0:
/home/mantadakis/Sources/TRIQS/master/cthyb.src/c++/impurity_trace.hpp: In member function ‘void cthyb::impurity_trace::try_replace(const oplist_t&)’:
/home/mantadakis/Sources/TRIQS/master/cthyb.src/c++/impurity_trace.hpp:401:62: warning: throw will always call terminate() [-Wterminate]
   if (!backup_nodes.is_index_reset()) TRIQS_RUNTIME_ERROR << "impurity_trace: improper use of try_replace()";

**Comment by krivenko** [comment]
Hi Daniil,

This error message is often a sign of an unphysical hybridization function.

**Comment by dmantadakis** [comment]
Ok! I will double check everything and I will let you know in a while!

**Comment by dmantadakis** [comment]
Thanks a lot Igor!! I had a mistake far before I reach the Solver, in the hamiltonian which was producing as you said a wrong Weiss field!
