### ISSUE TITLE
Difference in tutorial code results

### ISSUE THREAD

**Issue by hjuntaf** [TRIQS/cthyb#55]
Dear experts,

Hi, I have recently installed TRIQS and tested tutorial codes.
Once testing the Bethe lattice DMFT code (which is in 'Documenation - User Guide - Building DMFT calculations'),
I found that my results do not show the same as your data given at the bottom of the tutorial page.

I used the source code attached in the tutorial section (https://triqs.ipht.cnrs.fr/1.4/applications/cthyb/guide/dmft.html
https://triqs.ipht.cnrs.fr/1.4/applications/cthyb/_downloads/dmft.py
https://triqs.ipht.cnrs.fr/1.4/applications/cthyb/guide/dmft_plot.py ).

Although I run the code with various kinds of multi-core option, for example, np=1, 2, 4, 6, 8, 12, 16, and 24,
they did not match to your reference figure (data), too. 
The discrepancy in the iteration=4 data near omega=0 is noticeable, particularly.
Only the fact that Im(G) near omega=0 grows as 'np' is larger than 6 and the iteration number increase is a similar tendency.

I attached my np=1, np=4 and np=6 data (*.png) for reference. (
![np1_bethe](https://user-images.githubusercontent.com/29531799/27277409-205f5696-5519-11e7-81c7-f4fd560fd5a5.png)
![np4_bethe](https://user-images.githubusercontent.com/29531799/27277465-4cb8cf1a-5519-11e7-8471-413f8d6da7f2.png)
![np6_bethe](https://user-images.githubusercontent.com/29531799/27278312-ed64ed98-551b-11e7-8846-43be69897fa2.png)
)

Could you check this problem and let me know the environment of your testing-machine (for Bethe lattice tutorial) ?
Or, is there any machine-dependent thing for this problem?

**Comment by HugoStrand** [comment]
Dear @hjuntaf 

The `cthyb` code is a quantum monte-carlo based solver for quantum impurity problems. Hence there will always be stochastic noise in the solution. The relevant results for the physical system is only obtained once you converge the calculation also in terms of the number of montecarlo samples.

It seems like the DMFT example in the documentation is not converged in the sampling. It is unfortunate that you can not reproduce the same stochastic noise on your machine. However there are tests in the test suite for `cthyb` that actually checks the stochastic noise for some simple calculations.

So as long as your installation passes the tests you should not be worried that something is broke.

Best regards,
Hugo

**Comment by mferrero** [comment]
The example in the documentation has been produced by an earlier version of the solver. I have updated it with the current version and it does indeed look exactly like what you have found. You can see the new version of the documentation here:

https://triqs.ipht.cnrs.fr/1.x/applications/cthyb/guide/dmft.html

Cheers

**Comment by hjuntaf** [comment]
Thank you.
The latest one seems to match very well.

Sincerely,
Jun
