### ISSUE TITLE
Run all benchmarks and confirm that their tests passes

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/cthyb#57]
We want to check that all benchmarks passes, before releasing v1.5

The benchmarks are:
- 5+5
- anderson
- asymm_bath
- autopartition
- kanamori
- kanamori_offdiag
- legendre
- measure_g2 (ok)
- move_global
- nonint
- spinless

**Comment by JATIN199604** [comment]
Dear sir, I am trying to install TRIQS/CTHYB version 2.1.0, during make test some tests are passed but some tests are failled. How should I resolve these errors. 

jatin@jatin-HP-Laptop-14s-cr1xxx:~/triqs/cthyb.src$ make test
Running tests...
Test project /home/jatin/triqs/cthyb.src
      Start  1: anderson
 1/25 Test  #1: anderson .........................   Passed    2.10 sec
      Start  2: anderson_block
 2/25 Test  #2: anderson_block ...................   Passed    0.88 sec
      Start  3: anderson_qn
 3/25 Test  #3: anderson_qn ......................   Passed    0.71 sec
      Start  4: anderson_block_qn
 4/25 Test  #4: anderson_block_qn ................   Passed    0.83 sec
      Start  5: spinless
 5/25 Test  #5: spinless .........................   Passed    0.92 sec
      Start  6: spinless_qn
 6/25 Test  #6: spinless_qn ......................   Passed    0.85 sec
      Start  7: kanamori
 7/25 Test  #7: kanamori .........................   Passed    1.39 sec
      Start  8: kanamori_qn
 8/25 Test  #8: kanamori_qn ......................   Passed    1.62 sec
      Start  9: kanamori_offdiag
 9/25 Test  #9: kanamori_offdiag .................   Passed    1.23 sec
      Start 10: kanamori_offdiag_qn
10/25 Test #10: kanamori_offdiag_qn ..............   Passed    1.36 sec
      Start 11: legendre
11/25 Test #11: legendre .........................   Passed    0.91 sec
      Start 12: rbt
12/25 Test #12: rbt ..............................   Passed    0.05 sec
      Start 13: impurity_trace_atomic_gf
13/25 Test #13: impurity_trace_atomic_gf .........   Passed    0.35 sec
      Start 14: impurity_trace_bug_try_insert
14/25 Test #14: impurity_trace_bug_try_insert ....   Passed    0.38 sec
      Start 15: impurity_trace_op_insert
15/25 Test #15: impurity_trace_op_insert .........   Passed    0.33 sec
      Start 16: setup_Delta_tau_and_h_loc
16/25 Test #16: setup_Delta_tau_and_h_loc ........***Failed    4.17 sec
      Start 17: single_site_bethe
17/25 Test #17: single_site_bethe ................***Exception: SegFault  1.55 sec
      Start 18: atomic_observables
18/25 Test #18: atomic_observables ...............***Exception: SegFault  3.01 sec
      Start 19: kanamori
19/25 Test #19: kanamori .........................***Exception: SegFault  1.25 sec
      Start 20: slater
20/25 Test #20: slater ...........................***Exception: SegFault  1.68 sec
      Start 21: measure_static
21/25 Test #21: measure_static ...................***Exception: SegFault  1.25 sec
      Start 22: histograms
22/25 Test #22: histograms .......................***Exception: SegFault  1.20 sec
      Start 23: move_global
23/25 Test #23: move_global ......................***Exception: SegFault  1.21 sec
      Start 24: h5_read_write
24/25 Test #24: h5_read_write ....................***Exception: SegFault  1.25 sec
      Start 25: O_tau_ins
25/25 Test #25: O_tau_ins ........................***Exception: SegFault  1.33 sec

60% tests passed, 10 tests failed out of 25

Total Test time (real) =  31.94 sec

The following tests FAILED:
	 16 - setup_Delta_tau_and_h_loc (Failed)
	 17 - single_site_bethe (SEGFAULT)
	 18 - atomic_observables (SEGFAULT)
	 19 - kanamori (SEGFAULT)
	 20 - slater (SEGFAULT)
	 21 - measure_static (SEGFAULT)
	 22 - histograms (SEGFAULT)
	 23 - move_global (SEGFAULT)
	 24 - h5_read_write (SEGFAULT)
	 25 - O_tau_ins (SEGFAULT)
Errors while running CTest
Makefile:96: recipe for target 'test' failed
make: *** [test] Error 8

**Comment by HugoStrand** [comment]
Dear Jatin,

Thank you for reporting your problem. Unfortunately your issue is unrelated to the benchmarks that is the topic of this github issue.

Please, post your problem in a new issue so that we can separate the discussion and the topics. I think @Wentzell already have given you the same advice when you were posting on the Triqs github issues.

Best regards,
Hugo

**Comment by JATIN199604** [comment]
Dear sir, I was trying to solve the error but did not able to solve. Can
you suggest how should I resolve the error.

jatin@jatin-HP-Laptop-14s-cr1xxx:~/triqs/cthyb.src$ make test
Running tests...
Test project /home/jatin/triqs/cthyb.src
      Start  1: anderson
 1/25 Test  #1: anderson .........................   Passed    2.22 sec
      Start  2: anderson_block
 2/25 Test  #2: anderson_block ...................   Passed    0.84 sec
      Start  3: anderson_qn
 3/25 Test  #3: anderson_qn ......................   Passed    0.68 sec
      Start  4: anderson_block_qn
 4/25 Test  #4: anderson_block_qn ................   Passed    0.81 sec
      Start  5: spinless
 5/25 Test  #5: spinless .........................   Passed    0.91 sec
      Start  6: spinless_qn
 6/25 Test  #6: spinless_qn ......................   Passed    0.84 sec
      Start  7: kanamori
 7/25 Test  #7: kanamori .........................   Passed    1.33 sec
      Start  8: kanamori_qn
 8/25 Test  #8: kanamori_qn ......................   Passed    1.53 sec
      Start  9: kanamori_offdiag
 9/25 Test  #9: kanamori_offdiag .................   Passed    1.17 sec
      Start 10: kanamori_offdiag_qn
10/25 Test #10: kanamori_offdiag_qn ..............   Passed    1.29 sec
      Start 11: legendre
11/25 Test #11: legendre .........................   Passed    0.82 sec
      Start 12: rbt
12/25 Test #12: rbt ..............................   Passed    0.05 sec
      Start 13: impurity_trace_atomic_gf
13/25 Test #13: impurity_trace_atomic_gf .........   Passed    0.33 sec
      Start 14: impurity_trace_bug_try_insert
14/25 Test #14: impurity_trace_bug_try_insert ....   Passed    0.35 sec
      Start 15: impurity_trace_op_insert
15/25 Test #15: impurity_trace_op_insert .........   Passed    0.30 sec
      Start 16: setup_Delta_tau_and_h_loc
16/25 Test #16: setup_Delta_tau_and_h_loc ........***Failed    3.86 sec
      Start 17: single_site_bethe
17/25 Test #17: single_site_bethe ................***Exception: SegFault
 1.32 sec
      Start 18: atomic_observables
18/25 Test #18: atomic_observables ...............***Exception: SegFault
 3.11 sec
      Start 19: kanamori
19/25 Test #19: kanamori .........................***Exception: SegFault
 1.30 sec
      Start 20: slater
20/25 Test #20: slater ...........................***Exception: SegFault
 1.74 sec
      Start 21: measure_static
21/25 Test #21: measure_static ...................***Exception: SegFault
 1.20 sec
      Start 22: histograms
22/25 Test #22: histograms .......................***Exception: SegFault
 1.22 sec
      Start 23: move_global
23/25 Test #23: move_global ......................***Exception: SegFault
 1.17 sec
      Start 24: h5_read_write
24/25 Test #24: h5_read_write ....................***Exception: SegFault
 1.22 sec
      Start 25: O_tau_ins
25/25 Test #25: O_tau_ins ........................***Exception: SegFault
 1.23 sec

60% tests passed, 10 tests failed out of 25

Total Test time (real) =  31.15 sec

The following tests FAILED:
16 - setup_Delta_tau_and_h_loc (Failed)
17 - single_site_bethe (SEGFAULT)
18 - atomic_observables (SEGFAULT)
19 - kanamori (SEGFAULT)
20 - slater (SEGFAULT)
21 - measure_static (SEGFAULT)
22 - histograms (SEGFAULT)
23 - move_global (SEGFAULT)
24 - h5_read_write (SEGFAULT)
25 - O_tau_ins (SEGFAULT)
Errors while running CTest
Makefile:96: recipe for target 'test' failed
make: *** [test] Error 8



Thanks and Regards
Jatin

**Comment by HugoStrand** [comment]
Dear Jatin,

Please post your problem in a new issue on this repository. After you have done that I will be happy to try to help you. If you need guidance on how to create a new issue please read this tutorial:

https://help.github.com/en/articles/creating-an-issue

Best regards,
Hugo

**Comment by JATIN199604** [comment]
Dear Hugo,
I successfully run the dmftproj program for the compound  SrVO3. When I
initialize with help of the python script, I am getting this error.
jatin@jatin-HP-Laptop-14s-cr1xxx:~/SrVO3$ pytriqs SrVO3.py
pytriqs: command not found

I will be thankful for your suggestion.

Regards,
Jatin

**Comment by JATIN199604** [comment]
Dear Hugo,
I run the  python script with python command for SrVO3. The converter does
not produce any output for the hdf5 file. Here  I have given the python
script   with the result.
jatin@jatin-HP-Laptop-14s-cr1xxx:~/SrVO3$ python SrVO3.py
Starting on 1 Nodes at : 2019-08-02 10:37:58.105760
jatin@jatin-HP-Laptop-14s-cr1xxx:~/SrVO3$ Converter.convert_dft_input()
>

Your suggestion will be helpful.

Regards,
Jatin

**Comment by Wentzell** [comment]
@JATIN199604 Given that you continue to duplicate your issues on multiple lists even after we instructed you **multiple** times not to do so I have to block your account.
