### ISSUE TITLE
Configuration, finalize the move to mc_generic in triqs.

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/cthyb#60]
@parcollet one of the points discussed 24.07.2017.

We want to get rid of the `configuration` in `cthyb` all together  since the information is already contained in the trace.

How to accomplish this? Priority?

**Comment by krivenko** [comment]
Before you start doing this, please check `c++/moves/global.[h|c]pp`. I remember using `configuration` for some purpose there.

**Comment by HugoStrand** [comment]
This discussion has become outdated. I am closing the issue for now.
