### ISSUE TITLE
Semi automatic generation of the c++2py cthyb_desc.py file

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/cthyb#64]
The current state is entangled due to:

1. the CMake flag for complex hybridization function and determinant,
2. the wrapping of cthyb.solver and atomdiag in the same desc file.

We need to solve both, but agreed that separating `atomdiag` by it being merged in `triqs`.

**Comment by krivenko** [comment]
* I do not see how generated `cthyb_desc.py` depends on those complex flags...
* You want to completely eliminate the need for manual adjustment of `cpp2py`-generated description files, don't you? Let me ask a general question: Why do we need description files at all? If they are not meant to be manually changed, why not generate `*_wrap.cpp` right away and ship it together with the sources? We already do this with `*_converters.hxx`.

**Comment by HugoStrand** [comment]
This issue has been solved by the move of atom_diag to triqs and the recent updates in cpp2py and triqs 2.0.
