### ISSUE TITLE
Building without NFFT

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/cthyb#65]
Should we support building `cthyb` without `nfft`?

**Comment by tayral** [comment]
I guess that would be useful if nfft is not necessary for all parts of the code. If not possible, it would be nice if the version requirement were indicated in the documentation. For instance, NFFT 3.2.3 seems not to be enough: it yields the error:
```bash
In file included from /home/tayral/Work/TRIQS_1.6/source/cthyb/c++/./measures/../nfft_array.hpp:26:0,
                 from /home/tayral/Work/TRIQS_1.6/source/cthyb/c++/./measures/g4_iw.hpp:27,
                 from /home/tayral/Work/TRIQS_1.6/source/cthyb/c++/solver_core.cpp:42:
/home/tayral/Work/TRIQS_1.6/source/cthyb/c++/triqs/experimental/nfft_buf.hpp: Dans la fonction membre ‘void triqs::experimental::nfft_buf_t<Rank>::do_nfft()’:
/home/tayral/Work/TRIQS_1.6/source/cthyb/c++/triqs/experimental/nfft_buf.hpp:210:25: erreur : ‘struct nfft_plan’ has no member named ‘flags’
           if (plan_ptr->flags & PRE_ONE_PSI) nfft_precompute_one_psi(plan_ptr.get());
                         ^~~~~
make[2]: *** [c++/CMakeFiles/cthyb_c.dir/solver_core.cpp.o] Erreur 1
make[1]: *** [c++/CMakeFiles/cthyb_c.dir/all] Erreur 2
make: *** [all] Erreur 2
```
... but the latest (nfft.3.3.2) work (but this is not detected by cmake).

**Comment by krivenko** [comment]
> Should we support building cthyb without nfft?

Does building without NFFT implies building without G^4 measurement?
This is how it was done in the first place. The problem is that compile-time switches make Python wrapping messy.

**Comment by HugoStrand** [comment]
Dear Thomas and Igor,

I am working on this, the python wrapping is no problem, now that we are
using std::optional for all sampled quantities, and all getters are removed
in favour of direct access to member quantities.

I just have to figure out how to selectively run the python tests...

I have a little docker instance setup for building triqs/cthyb/unstable
without the nfft library, in case you want to have a look:
https://github.com/HugoStrand/triqs_docker

Best, Hugo

**Comment by HugoStrand** [comment]
I have made NFFT optional with commit 80fdd5ee2d356908473514238774f29f9c7bf267 which solves part of the problem.

The remaining issue is how to impose version requirements on FindNFFT, this will have to be pushed to Triqs where the `FindNFFT.cmake` file resides..

@tayral If you can please try to build `cthyb/unstable` without NFFT and let me know if it works out for you.

Best, Hugo

**Comment by tayral** [comment]
Yes, it works without NFFT now (would it not be even nicer if I could choose, by setting a cmake option USE_NFFT, to use it or not?). Thanks!
