### ISSUE TITLE
Cmake options HYBRIDISATION_IS_COMPLEX and LOCAL_HAMILTONIAN_IS_COMPLEX don't add any compile definitions

### ISSUE THREAD

**Issue by Wentzell** [TRIQS/cthyb#74]
Currently the cmake options HYBRIDISATION_IS_COMPLEX and LOCAL_HAMILTONIAN_IS_COMPLEX
serve only as a switch for a few tests.

They should be adding the corresponding compiler definitions
```cmake
if(HYBRIDISATION_IS_COMPLEX)
  add_definitions(-DHYBRIDISATION_IS_COMPLEX)
endif()

if(LOCAL_HAMILTONIAN_IS_COMPLEX)
  add_definitions(-DLOCAL_HAMILTONIAN_IS_COMPLEX)
endif()
```
so the code is properly compiled for the complex functionality.

**Comment by parcollet** [comment]
isn't the role of the #cmakedefine in config.hpp.in ?

Cf https://cmake.org/cmake/help/v3.2/command/configure_file.html?highlight=cmakedefine

**Comment by Wentzell** [comment]
Ah ok. Didn't know that yet!
