### ISSUE TITLE
Question: Error in CT-HYB. Why?

### ISSUE THREAD

**Issue by dmantadakis** [TRIQS/cthyb#76]
Dear all,

I have built up an interaction hamiltonian H_int but when I give it into the solver I get the following error message:

###############################################################
---- There is 1 error in Python -> C++ transcription for the class solve_parameters_t
1 The parameter h_int does not have the right type : expecting many_body_op_t in C++, but got 'pytriqs.operators.operators.Operator' in Python.
################################################################ 

Any ideas??

INFO: I store the h_int into a python dictionary like:
H["test"] = H_int 
and I call the solver as 
S.solve(h_int =H["test"], **solver_parameters)

Thanks!

**Comment by HugoStrand** [comment]
Dear @dmantadakis,

Could you please post your setup and run python scripts? Or even better a minimal example reproducing your problem. I.e., a script that stores your Hamiltonian and then tries to read it from a hdf5 file.

I suspect that there is an import statement missing in the script where you run the `S.solve(...)`. If you do not explicitly import the second quantization operators they will not have the correct type when you read them up from the hdf5-archive.

Cheers, Hugo

**Comment by dmantadakis** [comment]
Thanks for your reply!

1) In all my scripts I import

from pytriqs.operators.operators *
from pytriqs.operators.util *

2) Just before the solver I print out the type of the hamiltonian that I will feedback and I get
######## Interaction type: <type 'pytriqs.operators.operators.Operator'>

3) I don't read from any HDF archive. I create the interaction in one method of a general python class and I call this attribute (python dictionary) when I need to solve in my self_consistency method of the class.

**Comment by HugoStrand** [comment]
You are welcome. :) 

Could you please make a minimal example so that I can reproduce your error?

Best, Hugo

**Comment by dmantadakis** [comment]
I am trying to create a small script to reproduce the error. While doing this in an ipython notebook I get 
the following error and the kernel dies:

terminate called after throwing an instance of 'triqs::runtime_error'
  what():  .. Triqs runtime error at /home/mantadakis/Sources/TRIQS/master/triqs.build/pytriqs/operators/operators_wrap.cpp : 339
Severe internal error : _c is null in py2c for type many_body_operator !

Maybe it means something to you (or I make a terrible mistake)

Best,
Danny

**Comment by HugoStrand** [comment]
Dear Danny,

It is not easy to debug without seeing the script/code that produces the error.

Best, Hugo

**Comment by gkraberger** [comment]
Hi, 
also a wild guess without seeing your script, but I've seen that error when supplying a complex Hamiltonian to a CTHyb compiled without ` -DLOCAL_HAMILTONIAN_IS_COMPLEX=ON`.

Maybe check if that's the case.

**Comment by dmantadakis** [comment]
After some time I managed to detect (I think) where the problem originates. Consider the following script

import pytriqs.utility.mpi as mpi
from pytriqs.operators.util import *
from pytriqs.operators.operators import *
 
# Define the variable to be distributed
h_int = None
# Construct the hamiltonian only in master node
if mpi.is_master_node():
    h_int = 1.0 * n("up",0) * n("down",0)
print h_int # HERE IT CAN PRINT OUT THE OPERATOR
# Broadcast the hamiltonian to the other cores/nodes
h_int = mpi.bcast(h_int)
print("Broadcasted in mpi-rank: %s"%mpi.rank)
mpi.barrier()

# Get the 'type'
print("Type of object: %s (rank = %s)"%(type(h_int),mpi.rank))
mpi.barrier()

# Try to print it out
print("Operator: %s (rank = %s)"%(h_int,mpi.rank))

================================
Then I get the following ERROR message
Starting on 1 Nodes at : 2017-09-19 19:46:41.542546
1*C^+(down,0)C^+(up,0)C(up,0)C(down,0)
Broadcasted in mpi-rank: 0
Type of object: <type 'pytriqs.operators.operators.Operator'> (rank = 0)
terminate called after throwing an instance of 'triqs::runtime_error'
  what():  .. Triqs runtime error at /home/mantadakis/Sources/TRIQS/master/triqs.build/pytriqs/operators/operators_wrap.cpp : 339

Severe internal error : _c is null in py2c for type many_body_operator !
.. Error occurred on node 0

**Comment by dmantadakis** [comment]
The code translates to Markdown. Where should I post it to be more convenient for you to reproduce the error?

**Comment by krivenko** [comment]
Hi Daniil,

Check this out: https://github.com/TRIQS/triqs/issues/329
The issue was fixed on the `unstable` branch.

**Comment by dmantadakis** [comment]
Thanks a lot!!! I see... since I use the stable version I will find a work-around to do the job! 

All the best,
Danny

**Comment by HugoStrand** [comment]
Dear Danny,

To write formatted and highlighted code on github please see their guid to the Markdown syntax:
https://guides.github.com/features/mastering-markdown/

@krivenko, thank you for helping out :)

I am closing this issue for now, please reopen if needed.

Best, Hugo
