### ISSUE TITLE
[unstable] Missing parameters.rst

### ISSUE THREAD

**Issue by krivenko** [TRIQS/cthyb#77]
Compilation of the docs fails with the following message:
```
make[2]: *** No rule to make target '/home/igor/Physics/TRIQS/cthyb.git/doc/reference/parameters.rst', needed by 'doc/html/contents.html'.  Stop.
```
`${src}/doc/reference/parameters.rst` is a broken symlink pointing at `../../python/triqs_cthyb/solver_core_parameters.rst`

I could not find `solver_core_parameters.rst` neither in the sources, nor in the build directory.
What is going on?
Must it be generated by `c++2rst` during compilation?

**Comment by parcollet** [comment]
I removed it, it seemed useless
since the .solve method has the same info in its doc string.
Indeed, I forgot to check the building of the doc in cthyb, it is not in the CI.

**Comment by HugoStrand** [comment]
@parcollet which `.solve` method  do you refer to?

The `.solve` method of the `pytriqs` `cthyb.Solver` class does not contain the same parameters as the wrapped `c++` cthyb-solver (called `SolverCore`). It's docstring only documents the additional features (tail fitting) added on the python level.

How can we generate the `sover_core_parameters.rst` using `c++2rst` again?

**Comment by HugoStrand** [comment]
Dear Olivier,

This is still failing when building `cthyb` with docs.

```
make[2]: *** No rule to make target `../doc/reference/parameters.rst', needed by `doc/html/contents.html'.  Stop.
```

Can I remove the reference to `../doc/reference/parameters.rst` in the docs before we have this fixed?

**Comment by HugoStrand** [comment]
Now fixed
