### ISSUE TITLE
Fidelity susceptibility (feature request/question)

### ISSUE THREAD

**Issue by patrikthunstrom** [TRIQS/cthyb#80]
When I was looking for a non-expensive way to identify quantum phase transitions in a multi-orbital setting I found something called "Fidelity susceptibility" (PRL 115, 236601 (2015)). What it does in essence is to see if the operators in the local trace have a tendency to bunch up, or if they are uniformly spread over beta. 

The tree implementation of the local trace should as far as I can see be particularly favourable to measure the degree of bunching of the local operators. One way would be to store one histogram for each height with the (tau_max - tau_min)/#operators for the corresponding branches. Another way would be a histogram of the distance from the leaf to its branch. The simplest but also roughest way would be to do what they use in the paper, i.e. to split the local trace into a left [0,beta/2] and a right [beta/2,beta] part and look at the perturbation order for the two segments; (<k_L k_R> - <k_L><k_R>)/lambda^2, where lambda is proportional to the first moment of the hybridization function.

So, my question/request is, would it be possible to implement something like this (without to much work of course), or have you already implemented something equivalent under another name?

Best,
Patrik

**Comment by parcollet** [comment]
Looks interesting.
 I suggest to discuss this in private, cc @HugoStrand
