### ISSUE TITLE
[unstable] parameters for G2

### ISSUE THREAD

**Issue by francoisjamet** [TRIQS/cthyb#87]
Dear TRIQS team,

I'm trying to use TRIQS to  measure G2. 
By using the script measure_g2.py in the Benchmark repository.

I have two questions concerning the parameters : 
1)   estimate_nfft_buf_size 
When I call  estimate_nfft_buf_size(gf_struct,S.perturbation_order) as in measure_g2.py (L110), 
I got : 
```
  File "vertexll.py", line 132, in <module>
    p["nfft_buf_sizes"] = estimate_nfft_buf_size(gf_struct,S.perturbation_order)
  File "/home/jamet/opt/triqsunstable/lib/python2.7/site-packages/triqs_cthyb/util.py", line 30, in estimate_nfft_buf_size
    if not bn in pert_order_histograms:
TypeError: unhashable type: 'list'
```
2) measure_G2_blocks 
I would like to restrict the G2 to few blocks :
my gf_struct is defined as below in my script
```
gf_struct = op.set_operator_structure(['up','down'],['f','h'],False)
```
So, as in measure_g2.py I did : 
```
g2_blocks = set([('up_f', 'up_f')])
p["measure_G2_blocks"] = g2_blocks
```
but I got the following error :
```
    S.solve(h_int=H_int,**p)
  File "/home/jamet/opt/triqsunstable/lib/python2.7/site-packages/triqs_cthyb/solver.py", line 116, in solve
    solve_status = SolverCore.solve(self, **params_kw)
TypeError: 
---- There is 1 error in Python -> C++ transcription for the class cthyb::solve_parameters_t

1 The parameter measure_G2_block_order does not have the right type : expecting cthyb::block_order in C++, but got 'str' in Python.
```

thanks for your help,

françois

**Comment by HugoStrand** [comment]
Dear François,

If you still have issues with this, could you put together a minimal example script that produces the error? I think we fixed the `estimate_nfft_buf_size` issue previously, right?

Best regards,
Hugo

**Comment by HugoStrand** [comment]
Solved over private communication. Please reopen if needed. Best, Hugo
