### ISSUE TITLE
 Feeds cthyb with Delta instead of G0 

### ISSUE THREAD

**Issue by francoisjamet** [TRIQS/cthyb#91]
Dear TRIQS Team,

It would be useful to be able to feed the cthyb solver with the Hybridization fct and the impurity level instead of G0.

thanks,

françois

**Comment by parcollet** [comment]
Yes, we agree.
To be implemented, that is easy.

**Comment by jkarp314** [comment]
@Wentzell I think this issue can be closed now that the Delta interface is in unstable

**Comment by Wentzell** [comment]
Yes, this was fixed in https://github.com/TRIQS/cthyb/pull/141. Thank you @jkarp314
