### ISSUE TITLE
CT_HYB 2.0 is not working with the Complex Cmake attributes

### ISSUE THREAD

**Issue by marcel-klett** [TRIQS/cthyb#92]
Hey,

I installed triqs2.0 and also CT_HYB without any specific cmake flags. But then i wanted to turn on the two things

Hybridisation_is_complex=ON
Local_hamiltonian_is_complex=ON

which lead to failed tests, when i run 'make test'.

Best regards 
Marcel

**Comment by parcollet** [comment]
Sorry about that.
@Wentzell : this configuration is not in the CI ?
@HugoStrand : can you have a look ?

**Comment by HugoStrand** [comment]
Dear Marcel,

The failing tests has been fixed on the `unstable` branch. Could you please try to build and run the tests on that branch?

Best regards,
Hugo

**Comment by marcel-klett** [comment]
Hello, 

the unstable branch is working without any errors! Thanks!

Best regards
Marcel

**Comment by HugoStrand** [comment]
Super! Thank you for testing. 👍 

Best, Hugo
