### ISSUE TITLE
Add NFFT to dependency list in docs

### ISSUE THREAD

**Issue by pjc277** [TRIQS/cthyb#97]
Hello,

Could I ask for the name of the NFFT package that needs to be installed before CTHyb can be compiled? It would be helpful if this information is available on the online install instructions as well.

Best,

Peter

**Comment by HugoStrand** [comment]
Dear Peter,

Thank you for the feedback. The package is NFFT3 from TU Chemnitz 
https://www-user.tu-chemnitz.de/~potts/nfft/
Depending on your system it might be readily available in your software package repository.

The default of `cthyb` is to look for NFFT for the two particle sampling. However, if you only want the basic functionality for sampling the single particle Greens function you can run cmake with `cmake -DMeasureG2=OFF ...` and then you no longer need NFFT to compile `cthyb`.

The docs do need updating on this. Sorry.

Please let me know if this solves your issue with building.

Best, Hugo
