### ISSUE TITLE
Test fail with TRIQS V2.0: single_site_bethe and slater

### ISSUE THREAD

**Issue by henhans** [TRIQS/cthyb#99]
Dear TRIQS team,

I am trying to install cthyb with the newest TRQIS V2.0 but I met the following error when
testing the single_site_bethe and slater. My system is ubuntu18.04 and the compiler is
gcc-7.3.0 and clang6.

For single_site_bethe, the error seems large 0.029...
https://gist.github.com/henhans/c6867b1d58c95a04d09103ce8a951b96

For slater, the error is small 1e-6
https://gist.github.com/henhans/7bf0eb32895ad5e9a53b68b2764c6def

I wonder how should I resolve these two fails?

Thank you,
Tsung-Han

**Comment by HugoStrand** [comment]
Dear henhans,

Thank you for reporting the broken tests. 

Right now these are "know failures" for `cthtb/master` and also the reason why we have not released `cthyb/2.0.x` yet.

There is an issue with the Matsubara Fourier transform in `triqs/2.0.0` that effects `cthyb`. This is currently being worked on and once it is fixed we will start releasing `cthyb/2.0.x`.

Please stay tuned.

Best regards,
Hugo

**Comment by mueslo** [comment]
Why did you close this issue if this is not fixed yet? It makes it harder for other people encountering this to actually see it is being worked on.

Issues are meant to track progress on bugs, and this one isn't fixed yet. Closing them implies they are fixed (at least upstream).

**Comment by HugoStrand** [comment]
Dear Mueslo, It is, to the best of my knowledge, now fixed on the 2.1.x branch. If you are having trouble with this please reopen the issue and report your problem.
